<<<<<<< HEAD:database-files/sample_data.sql
-- System Administrator Data
=======
USE global;
>>>>>>> 0ab4d98f295f7b18764cc84dcdcba1a64e9fa3d4:database-files/02sample_data.sql
INSERT INTO system_administrator VALUES
('brooke32@example.net', 'Donald', 'Campbell', 'Support Specialist'),
('melissamoore@example.com', 'Paul', 'Andrews', 'Content Manager'),
('blivingston@example.org', 'Megan', 'Murphy', 'Content Manager'),
('brianlee@example.net', 'Eugene', 'Harmon', 'Content Manager'),
('deniseanderson@example.org', 'Katherine', 'Mckay', 'Support Specialist'),
('wmichael@example.org', 'Ronald', 'Mathis', 'Content Manager'),
('andersoncarol@example.com', 'Joseph', 'Alvarez', 'Content Manager'),
('delgadochristina@example.net', 'Troy', 'Le', 'Content Manager'),
('michael37@example.net', 'Roger', 'Parker', 'Support Specialist'),
('simonandrew@example.net', 'Patricia', 'Carrillo', 'Support Specialist');

-- Mentee Data
INSERT INTO mentee VALUES
('8', '10', 'Martin', 'Hill', 'madeline43@example.net', 'French', 'Beginner'),
('2', '10', 'Brenda', 'Jensen', 'davidtodd@example.org', 'Japanese', 'Beginner'),
('4', '8', 'Madison', 'Young', 'amanda24@example.net', 'Spanish', 'Beginner'),
('7', '10', 'Jim', 'Aguilar', 'mfarmer@example.com', 'Chinese', 'Beginner'),
('6', '10', 'Matthew', 'Baker', 'plyons@example.com', 'Chinese', 'Intermediate'),
('10', '8', 'Alisha', 'Frank', 'petersonjennifer@example.org', 'Chinese', 'Intermediate'),
('3', '6', 'Joshua', 'Gallegos', 'davidsonryan@example.com', 'French', 'Intermediate'),
('7', '8', 'Victoria', 'Sanders', 'jacksonamy@example.net', 'Chinese', 'Beginner'),
('6', '1', 'James', 'Patel', 'taylordrew@example.org', 'French', 'Advanced'),
('7', '7', 'Tracey', 'Camacho', 'ereilly@example.com', 'French', 'Fluent'),
('9', '2', 'Thomas', 'Smith', 'mfrederick@example.org', 'Spanish', 'Intermediate'),
('4', '1', 'Natalie', 'Poole', 'ksantiago@example.com', 'French', 'Intermediate'),
('10', '8', 'Chelsey', 'Nguyen', 'jody62@example.net', 'Chinese', 'Fluent'),
('5', '8', 'Chad', 'Hinton', 'froststuart@example.com', 'Japanese', 'Beginner'),
('8', '6', 'Donna', 'Crosby', 'davidflores@example.com', 'Spanish', 'Beginner'),
('5', '5', 'Amy', 'Scott', 'xkennedy@example.com', 'Spanish', 'Advanced'),
('3', '9', 'David', 'Nelson', 'andrea87@example.org', 'Spanish', 'Intermediate'),
('8', '6', 'Laura', 'Smith', 'david35@example.com', 'Chinese', 'Advanced'),
('3', '8', 'Christopher', 'Kramer', 'alleneric@example.org', 'French', 'Advanced'),
('10', '2', 'Elizabeth', 'Weaver', 'dylandavis@example.org', 'Chinese', 'Intermediate'),
('4', '4', 'Lisa', 'Padilla', 'dali@example.com', 'French', 'Intermediate'),
('3', '4', 'Christopher', 'Cochran', 'ztaylor@example.com', 'French', 'Intermediate'),
('7', '2', 'Daniel', 'Atkinson', 'pgarcia@example.net', 'Chinese', 'Beginner'),
('2', '1', 'Whitney', 'Hill', 'tranangela@example.com', 'Chinese', 'Fluent'),
('1', '9', 'Amanda', 'Garcia', 'kathleenhogan@example.net', 'Japanese', 'Fluent'),
('9', '2', 'Douglas', 'Lawrence', 'martingregory@example.net', 'French', 'Beginner'),
('10', '3', 'Luis', 'Manning', 'hineskathy@example.org', 'Chinese', 'Intermediate'),
('2', '8', 'Ann', 'Shah', 'hzhang@example.org', 'French', 'Beginner'),
('1', '2', 'Leah', 'Daniels', 'hgalvan@example.org', 'French', 'Intermediate'),
('1', '5', 'Justin', 'Johnson', 'ischwartz@example.org', 'French', 'Fluent'),
('3', '7', 'Evan', 'Mcdonald', 'paulallen@example.org', 'Spanish', 'Advanced'),
('10', '3', 'Jose', 'Decker', 'michael18@example.org', 'Japanese', 'Beginner'),
('3', '10', 'Taylor', 'Mora', 'adamlowe@example.org', 'Japanese', 'Fluent'),
('10', '2', 'James', 'Clark', 'kristen51@example.net', 'Spanish', 'Fluent'),
('5', '9', 'Anthony', 'Bell', 'susan08@example.com', 'Chinese', 'Fluent'),
('10', '10', 'Cassandra', 'Jarvis', 'ericward@example.org', 'Japanese', 'Advanced'),
('7', '3', 'Christine', 'Holt', 'dennisbarnes@example.net', 'Japanese', 'Beginner'),
('4', '3', 'Kelly', 'Gomez', 'haneydeborah@example.net', 'Spanish', 'Advanced'),
('7', '3', 'Joshua', 'Callahan', 'bhutchinson@example.com', 'French', 'Intermediate'),
('5', '8', 'Richard', 'Robinson', 'thomasmann@example.net', 'Chinese', 'Beginner');

-- Mentor Data
INSERT INTO mentor VALUES
('6', '3', 'Ebony', 'Reed', 'abradshaw@example.com', 'Japanese', 'Tiffanyton, Guatemala', 'Fluent'),
('1', '1', 'Elaine', 'Miller', 'glennraymond@example.com', 'Japanese', 'Jamesville, Anguilla', 'Advanced'),     
('6', '2', 'Jennifer', 'Rose', 'bakermiguel@example.com', 'French', 'Lake Nicolehaven, Cote d'Ivoire', 'Advanced'),
('9', '8', 'Derrick', 'Lopez', 'wanda64@example.org', 'Chinese', 'Lawsonhaven, Vietnam', 'Advanced'),
('1', '9', 'Kelly', 'White', 'michael43@example.org', 'Spanish', 'Turnerstad, Israel', 'Advanced'),
('6', '8', 'Sabrina', 'Becker', 'danielsrussell@example.net', 'Chinese', 'West Amy, Armenia', 'Fluent'),        
('7', '5', 'Wanda', 'Hanson', 'earlnewton@example.com', 'Japanese', 'North Stephen, British Indian Ocean Territory (Chagos Archipelago)', 'Fluent'),
('6', '1', 'Cindy', 'Murray', 'briana26@example.com', 'Spanish', 'North Ronaldtown, Nepal', 'Advanced'),        
('6', '6', 'April', 'Martinez', 'taylor38@example.org', 'Chinese', 'Jamesberg, Mauritius', 'Fluent'),
('9', '9', 'Mark', 'Webb', 'sschmidt@example.org', 'Spanish', 'Jenkinsview, Chile', 'Advanced'),
('7', '9', 'Thomas', 'Hansen', 'sramirez@example.com', 'Japanese', 'Port David, Sweden', 'Fluent'),
('4', '10', 'Joshua', 'Schwartz', 'riveramikayla@example.net', 'Spanish', 'Lake David, Bhutan', 'Advanced'),    
('3', '7', 'Tanya', 'Green', 'abean@example.net', 'French', 'Mariastad, Liberia', 'Advanced'),
('9', '4', 'Nicholas', 'Perez', 'paulacain@example.com', 'Spanish', 'Rodriguezstad, Hong Kong', 'Advanced'),    
('10', '3', 'Michael', 'Hopkins', 'sanchezapril@example.org', 'Spanish', 'South Todd, Lao People's Democratic Republic', 'Fluent'),
('6', '3', 'Sarah', 'Pearson', 'aingram@example.net', 'French', 'Jonathanfurt, Cape Verde', 'Fluent'),
('9', '8', 'Donna', 'Ingram', 'katiemay@example.org', 'French', 'Lake Marcusmouth, Korea', 'Advanced'),
('2', '8', 'Shannon', 'Ortega', 'pcooper@example.org', 'Japanese', 'East Blaketon, Cocos (Keeling) Islands', 'Fluent'),
('2', '7', 'Alec', 'Hodges', 'ulin@example.net', 'Spanish', 'Shepardton, Turkmenistan', 'Fluent'),
('8', '7', 'Henry', 'Wallace', 'jacobsthomas@example.net', 'Spanish', 'Murrayburgh, Togo', 'Fluent'),
('6', '5', 'Lisa', 'Castillo', 'richardblack@example.net', 'Chinese', 'East Patriciabury, Denmark', 'Fluent'),  
('1', '1', 'Christine', 'Lewis', 'anewman@example.net', 'Spanish', 'Carlosview, Nauru', 'Advanced'),
('3', '3', 'Ashley', 'Gutierrez', 'daviscynthia@example.com', 'Spanish', 'East Richardmouth, Malaysia', 'Advanced'),
('6', '2', 'Jasmine', 'Jordan', 'julia36@example.org', 'Chinese', 'East Deborahland, Iran', 'Advanced'),        
('10', '10', 'Teresa', 'Murphy', 'ograves@example.org', 'Japanese', 'Youngtown, Martinique', 'Advanced'),       
('1', '8', 'Megan', 'Poole', 'edwardsedward@example.org', 'Japanese', 'South Tyler, Chad', 'Fluent'),
('8', '1', 'Scott', 'Baker', 'rarmstrong@example.org', 'Japanese', 'South Kimberly, Brazil', 'Advanced'),       
('4', '10', 'Blake', 'Montgomery', 'phillipsthomas@example.org', 'Chinese', 'Danielleburgh, Saint Martin', 'Fluent'),
('2', '3', 'Lauren', 'Ward', 'thomas84@example.net', 'Spanish', 'Turnerport, Isle of Man', 'Fluent'),
('7', '7', 'Michael', 'Jimenez', 'navarrolinda@example.com', 'Chinese', 'New Julie, Dominica', 'Advanced'),     
('9', '8', 'Victor', 'Swanson', 'fblack@example.com', 'French', 'Lake Jade, Reunion', 'Advanced'),
('9', '2', 'Nicholas', 'Dorsey', 'cummingsyolanda@example.net', 'Japanese', 'Gallagherberg, Bhutan', 'Fluent'), 
('10', '4', 'Jeremy', 'Haney', 'clarkchristina@example.net', 'Chinese', 'South William, Albania', 'Fluent'),    
('1', '4', 'Lauren', 'Garrison', 'lindsey06@example.com', 'Spanish', 'Garciachester, Turks and Caicos Islands', 'Advanced'),
('6', '4', 'James', 'Douglas', 'joshuamoore@example.net', 'Chinese', 'Erinchester, Paraguay', 'Advanced'),      
('6', '4', 'Katelyn', 'Lewis', 'jacqueline63@example.org', 'French', 'Rebeccafort, China', 'Fluent'),
('9', '9', 'Kevin', 'Holmes', 'ashlee02@example.com', 'Chinese', 'Port Melissafort, Guinea-Bissau', 'Fluent'),  
('4', '9', 'Thomas', 'Burch', 'sara43@example.org', 'French', 'Danside, Palau', 'Advanced'),
('6', '3', 'Anthony', 'Rivas', 'brendathomas@example.org', 'Spanish', 'South Barbara, Antigua and Barbuda', 'Fluent'),
('10', '7', 'Christopher', 'Monroe', 'perezdavid@example.org', 'French', 'North Margaret, Palau', 'Fluent');    

-- Learning Path Data
INSERT INTO learning_path VALUES
('40', '10', 'Module 1', 'Pressure name fall if line process.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('2', '1', 'Module 4', 'Last keep support ability beyond identify.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),
('11', '8', 'Module 4', 'Team pay test tell section try.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('3', '8', 'Module 3', 'Get decide already task smile Mrs power.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('6', '7', 'Module 2', 'Book enough friend.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),
('24', '8', 'Module 2', 'Fish send prepare benefit movie.', 'Milestone 1, Milestone 2, Milestone 3', 'Pending'),
('31', '5', 'Module 1', 'Face cold start church.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),     
('35', '7', 'Module 1', 'Audience know pattern human.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),   
('4', '3', 'Module 5', 'Without billion team our resource on window.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('19', '8', 'Module 2', 'Use represent fear.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('13', '5', 'Module 5', 'Similar research red now. Media popular above.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('34', '7', 'Module 3', 'Summer that value draw.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),       
('20', '4', 'Module 4', 'His support article.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('27', '5', 'Module 3', 'Phone half when wish page.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),
('14', '4', 'Module 3', 'Travel poor though consumer.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('37', '10', 'Module 5', 'Should affect data company offer give piece.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('4', '10', 'Module 1', 'Analysis pick task likely.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),  
('26', '5', 'Module 4', 'South story ask chair bad manager culture.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),
('17', '2', 'Module 3', 'Many mean they describe.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),       
('22', '5', 'Module 5', 'Term radio pretty economic day now stay.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('28', '5', 'Module 4', 'White surface these against third turn.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),
('30', '1', 'Module 4', 'Face road cultural. Leg hair chair.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('32', '10', 'Module 1', 'Usually amount suffer end establish figure.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('33', '9', 'Module 3', 'Fine television share nearly main.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('24', '3', 'Module 4', 'Significant research raise information must.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('18', '7', 'Module 4', 'Hour product appear end player.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('6', '6', 'Module 3', 'Series song condition over debate name onto.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('40', '6', 'Module 5', 'Admit her his senior.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('31', '2', 'Module 1', 'Memory fact glass mission choice ability reason.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('6', '6', 'Module 5', 'Card cut model together about. Drug movie may in.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('14', '9', 'Module 1', 'These inside fact think stand.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('13', '6', 'Module 4', 'Difference food site article.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('6', '9', 'Module 5', 'Actually grow thousand body.', 'Milestone 1, Milestone 2, Milestone 3', 'Pending'),     
('13', '2', 'Module 4', 'Song produce start artist worry woman.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('14', '1', 'Module 1', 'Other marriage brother carry stage speak.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),
('39', '6', 'Module 4', 'North middle prepare vote produce.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('9', '3', 'Module 3', 'Machine necessary hair control.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('8', '4', 'Module 4', 'For team part science group last.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('5', '5', 'Module 2', 'Fund do suggest beat.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),        
('23', '2', 'Module 2', 'Maintain home move per teach ask population very.', 'Milestone 1, Milestone 2, Milestone 3', 'Open');

-- Progress Data
INSERT INTO progress VALUES
('12', '18', 'Not Started', '2024-02-24'),
('11', '33', 'Open', '2024-05-08'),
('40', '17', 'Pending', '2024-05-27'),
('24', '7', 'Completed', '2024-01-17'),
('2', '23', 'Completed', '2024-11-13'),
('16', '31', 'Pending', NULL),
('40', '15', 'Not Started', NULL),
('22', '26', 'Pending', '2024-01-19'),
('13', '2', 'Pending', NULL),
('17', '10', 'Completed', NULL),
('3', '29', 'Not Started', '2024-06-16'),
('22', '9', 'Completed', NULL),
('11', '32', 'Not Started', '2024-09-23'),
('17', '3', 'Open', '2024-01-02'),
('7', '11', 'In Progress', NULL),
('2', '2', 'Open', NULL),
('26', '26', 'In Progress', '2024-09-18'),
('27', '23', 'Pending', NULL),
('31', '4', 'Completed', '2024-02-06'),
('8', '27', 'In Progress', '2024-01-27'),
('24', '6', 'Not Started', NULL),
('9', '6', 'Pending', '2024-04-17'),
('23', '4', 'In Progress', '2024-03-11'),
('8', '38', 'Open', '2024-07-15'),
('36', '36', 'Open', '2024-09-03'),
('30', '2', 'In Progress', NULL),
('19', '30', 'Resolved', NULL),
('29', '21', 'In Progress', '2024-06-09'),
('31', '21', 'Completed', '2024-08-04'),
('10', '39', 'Pending', '2024-09-01'),
('22', '2', 'Pending', '2024-02-21'),
('32', '39', 'Not Started', '2024-11-19'),
('12', '1', 'Open', '2024-09-01'),
('22', '22', 'Resolved', '2024-06-04'),
('2', '29', 'In Progress', '2024-02-07'),
('11', '2', 'Not Started', '2024-01-06'),
('20', '24', 'Open', '2024-10-03'),
('21', '4', 'Resolved', NULL),
('34', '24', 'Open', '2024-10-12'),
('13', '40', 'Resolved', '2024-06-10');

-- Issue Report Data
INSERT INTO issue_report VALUES
('9', NULL, 'In Progress', 'Loss participant goal forward condition in. Receive individual during.'),
('26', '3', 'Completed', 'Help region road character performance. Bed candidate despite draw chair front still.'),
('16', NULL, 'Completed', 'Mission example news. Officer guess support hit. And place campaign as.'),
('1', '5', 'In Progress', 'Cover mind policy financial board people. Address talk later strong.'),
('36', '5', 'In Progress', 'Recognize board war be TV. Science player oil whom. Sort in should feeling thought.'),
('28', '3', 'Not Started', 'And huge total enjoy agree. Prove rich offer student evening rich cover.'),
('11', '1', 'Resolved', 'Until alone table whether. Wait imagine total collection charge source also hear.'),   
('34', NULL, 'In Progress', 'Many outside hot language scene thousand. Listen campaign black.'),
('23', NULL, 'Completed', 'Happy us how. Full you economy generation care he moment. Once drop mouth would may little perform.'),
('27', NULL, 'Resolved', 'Listen they item former already sea seven staff. Lead head wind fine home.'),
('20', NULL, 'Resolved', 'Continue move nature story. Per right opportunity. Guess upon why minute.'),
('36', NULL, 'Open', 'Believe speak capital east. Job save nice too usually rise staff conference.'),
('6', NULL, 'Not Started', 'Up why authority concern century half or.'),
('17', '6', 'Resolved', 'Generation hold remember apply oil team suddenly.'),
('33', NULL, 'In Progress', 'End forget your when significant read present. History successful deep alone administration if.'),
('13', '1', 'Not Started', 'Few miss action.'),
('22', '7', 'Resolved', 'And discussion beat modern. Grow money throughout open product let mouth.'),
('6', '7', 'Open', 'Why education positive material event risk. Sit I fine three.'),
('16', NULL, 'Completed', 'Serve lay wife south reach property follow.'),
('27', NULL, 'Pending', 'Entire memory difficult leg instead read feel color. Summer lose save option.'),       
('16', NULL, 'Open', 'Simple but season control end. Room interview every beat upon beat push.'),
('39', NULL, 'Resolved', 'Such edge pressure keep unit wind nearly mouth. Meet those either move gun present source.'),
('26', NULL, 'Pending', 'Huge job bit understand. Standard fish choose argue ever drive official. Always main space.'),
('27', '7', 'In Progress', 'Hand chance get.
Seem city should recent decision rather.'),
('22', NULL, 'Open', 'Assume show more popular. Ground bar though point.'),
('16', NULL, 'Pending', 'Business remember sign relationship local early. Drug action movement then.'),
('12', NULL, 'Resolved', 'During out minute. Apply whom support boy. And candidate oil value kid same whom.'),  
('18', '5', 'Open', 'Fill parent political gun decade possible single wrong. Picture friend campaign management mother.'),
('39', NULL, 'Pending', 'Miss employee from explain. If table sound these.'),
('32', NULL, 'Pending', 'However view stuff say whole today. Student decide player standard change bad space.'),
('37', '1', 'Not Started', 'State particular bag crime watch. Plan film together commercial pass cultural.'),   
('29', NULL, 'Completed', 'Toward economic sit impact. Explain material smile material.'),
('12', NULL, 'Not Started', 'Congress face national risk. Glass doctor read force red heavy.'),
('33', '3', 'Resolved', 'Skin sister would reduce theory. School full agency material dream contain issue statement.'),
('18', NULL, 'Open', 'Money brother fight difference. Good country imagine near.'),
('32', NULL, 'Not Started', 'Make boy short themselves yet. Chance design nothing nor.'),
('4', NULL, 'Completed', 'Effect body spend threat where challenge low suddenly.'),
('31', '8', 'In Progress', 'Professional argue college human. Industry begin girl husband top.'),
('24', NULL, 'Pending', 'Stand including sense cover agree. Former worry capital vote green.'),
('27', '7', 'Completed', 'Road them somebody wish. Stuff just chair cause pattern speech.');

-- Content Updates Data
INSERT INTO content_updates VALUES
('27', '3', 'People feel suddenly environment then benefit source. Cold send gun both executive agent.'),       
('39', '1', 'Question break a allow cup grow. While result future only. Make owner four official dark.'),       
('21', '10', 'College race project other what time.'),
('14', '6', 'Decade be decision different protect girl. Right generation force class teach.'),
('11', '6', 'Treatment treatment really that. Nature he sort you example.'),
('19', '1', 'Wall rate network speak. Firm different area method.'),
('23', '2', 'Way writer simply exactly newspaper both ability. Model discover day.'),
('25', '8', 'Color wide low with paper happy. Attack cost floor all.'),
('11', '7', 'Language discussion issue small memory. Relationship act too admit school information.'),
('34', '8', 'Determine position unit and in office. Recognize marriage bed hit.'),
('34', '1', 'One front program usually federal physical draw. Down allow citizen charge share herself west.'),  
('33', '5', 'Team commercial than realize concern senior. Benefit magazine democratic behind.'),
('11', '6', 'Together upon realize structure. Democratic management economy very memory.'),
('2', '7', 'Church single all miss care.'),
('35', '4', 'Western say per six forget once. Heart wear gas amount try.'),
('31', '8', 'Upon money manager himself the rest. Western too scientist treatment.'),
('19', '4', 'Discussion song may board. Talk onto environmental computer foot American finish.'),
('11', '3', 'Drug world school first protect foot first beat. Image land wide live toward trial.'),
('37', '3', 'Beautiful old study hair. Your baby speak. She increase line.'),
('17', '5', 'Agency fear month again service ago if.
Forget control very response white fund.'),
('12', '1', 'Message travel the marriage continue. Us so paper since risk scientist.'),
('26', '2', 'Seem sign both perform whatever. Pick southern usually wear.'),
('29', '3', 'True example far maybe. Picture loss send avoid.'),
('8', '6', 'Suddenly heavy image Democrat mouth community by.'),
('4', '4', 'Board rock ahead over human much guy. Air reach life thing show money.'),
('10', '10', 'Expect a environmental reach food think positive. Activity crime own trial note life research.'), 
('1', '1', 'Court focus performance pick. Like news star blue radio area.'),
('26', '7', 'Similar base job stock.'),
('28', '6', 'Analysis form trip tax marriage drug. Trial century indeed prevent.'),
('15', '2', 'Partner by of serious accept police. Draw weight mission mission.'),
('36', '2', 'Whom show eat.'),
('27', '8', 'Actually mother reality everybody trip. Vote vote people type process. Each although pass however.'),
('12', '3', 'Artist ball class shake nothing. Power family condition.'),
('30', '7', 'Later mother vote put food war window. Course again together television.'),
('13', '6', 'East up thought four method my number light. Beautiful we student suffer actually unit.'),
('29', '4', 'Occur police type sport live officer century forward. Apply speak her claim at born.'),
('3', '9', 'Yet near behind the. Prevent human each throughout rather physical right card.'),
('29', '5', 'Stand add base quite. Open in treat production American well machine.'),
('1', '2', 'Remain federal student final improve. At partner than recent different but analysis.'),
('38', '8', 'Civil threat imagine will collection prepare loss everyone. Realize language able join prove.');   

-- Session Data
INSERT INTO session VALUES
('16', '22', 'Room carry teach member indicate course.', '2024-01-02', '02:41:00'),
('38', '13', 'Deep shoulder offer by official.', '2024-05-10', '02:48:00'),
('20', '25', 'Analysis big mouth nor spend one trial.', '2024-06-08', '03:39:00'),
('10', '3', 'Pm plant try really approach much majority send.', '2024-03-23', '02:50:00'),
('5', '23', 'Media material ten beyond author room.', '2024-09-13', '03:48:00'),
('26', '13', 'Democratic doctor budget his buy much.', '2024-07-17', '03:07:00'),
('31', '39', 'None production idea nature.', '2024-06-21', '03:59:00'),
('8', '27', 'Story recent purpose house.', '2024-02-12', '01:32:00'),
('39', '39', 'Style meet people production.', '2024-01-08', '00:01:00'),
('2', '26', 'Rather suffer program rise wind safe service.', '2024-02-07', '01:58:00'),
('27', '35', 'Watch example Mrs church real common remember.', '2024-11-19', '01:15:00'),
('9', '9', 'Mouth if old line. Life effect opportunity.', '2024-01-04', '02:10:00'),
('35', '1', 'Understand bag year foot.', '2024-09-17', '01:23:00'),
('27', '29', 'Method allow level else movement accept.', '2023-12-27', '02:44:00'),
('37', '7', 'Live view senior create adult lead hour open.', '2024-03-23', '03:36:00'),
('18', '36', 'Test series join.', '2024-02-14', '00:12:00'),
('5', '7', 'Debate stop affect attorney.', '2024-05-14', '02:37:00'),
('23', '35', 'Compare special beautiful wait institution.', '2024-01-27', '03:53:00'),
('1', '11', 'Huge former education lot night song provide.', '2024-09-27', '00:08:00'),
('2', '4', 'Speak while avoid song.', '2023-12-24', '02:12:00'),
('26', '6', 'Here while organization just else.', '2024-06-18', '01:58:00'),
('4', '28', 'With assume pull success catch table poor.', '2024-05-28', '00:27:00'),
('14', '39', 'Need recently cultural shake participant school.', '2024-09-25', '02:19:00'),
('13', '16', 'Week politics picture end wait thank thus.', '2024-06-09', '01:34:00'),
('32', '26', 'Product understand however keep media.', '2024-09-13', '03:22:00'),
('9', '34', 'Question senior Mr deep simply.', '2024-09-29', '01:22:00'),
('34', '26', 'Word notice standard return across.', '2024-03-18', '02:03:00'),
('8', '28', 'Laugh that once moment key really.', '2024-08-26', '00:59:00'),
('40', '28', 'Garden police down fast.', '2024-11-17', '03:54:00'),
('2', '24', 'Network southern place laugh.', '2024-08-31', '00:54:00'),
('17', '5', 'Paper soon foot million wait contain rich.', '2024-04-03', '01:14:00'),
('24', '35', 'Read reflect garden.', '2024-11-29', '03:07:00'),
('27', '16', 'Join current same carry people practice behind.', '2023-12-06', '03:19:00'),
('15', '13', 'Country spring build board drive.', '2024-10-06', '01:11:00'),
('6', '40', 'Right eat every local also how safe.', '2023-12-23', '02:15:00'),
('21', '40', 'Middle finally store service serious network.', '2024-09-03', '03:43:00'),
('18', '26', 'Space standard probably mouth organization.', '2024-01-30', '00:21:00'),
('23', '15', 'Management ball question government sing century.', '2024-11-24', '00:20:00'),
('14', '29', 'So city continue training.', '2024-02-23', '00:53:00'),
('23', '16', 'Miss meet reason realize third.', '2024-04-18', '01:42:00');

-- Feedback Data
INSERT INTO feedback VALUES
('39', 'Should big such firm. Control book stop may arrive defense car physical.'),
('6', 'Stuff total deal its power. Police ball strategy finish. Serious through return message.'),
('13', 'Religious administration cell wife beyond. Situation since final commercial.'),
('11', 'Age few center analysis fact. Throw garden chance although section many.'),
('27', 'Could one plant inside chance door central. House song enter walk. Political draw white great.'),       
('3', 'Also whatever long ever out behind improve. Various offer health may write within.'),
('15', 'Exist hard on receive. Fear out window light culture.'),
('10', 'Enter represent any me. Month suggest million whose after structure program.'),
('34', 'Feel set main nor beyond these. Strong site away common. Land worker old east safe.'),
('16', 'Account since these around evening I wife issue. Seven foot energy trade image.'),
('35', 'Foreign officer less require.'),
('17', 'That effect better travel well help policy. Through second TV or film civil Mrs.'),
('11', 'Project trouble fact tough job last goal.'),
('10', 'Former along mission. Want hear walk only message.'),
('27', 'Nothing soon day factor sport prove. Certain financial program state.'),
('34', 'Congress yourself full skin story. Modern drop small order spend.'),
('31', 'Keep these author remain management they. Certain someone lead under human run able.'),
('8', 'Future total argue miss. Wear civil bill operation crime indeed.'),
('35', 'None will behind east. Gas wide order safe. Kind number employee so maintain mention five.'),
('23', 'Everybody financial beautiful never tax. Trouble deal represent second.'),
('15', 'Born case within bar believe radio.'),
('3', 'Forget world way news sing feel. Conference beautiful court themselves control.'),
('1', 'Discussion though president hard. Bank suffer challenge community. Buy address role.'),
('7', 'Scene shoulder money watch performance. Total word old simply. Measure most close.'),
('19', 'Rock another pick figure home phone. Food character eight argue determine put than rate.'),
('13', 'Stand agreement oil long employee. Room that bar believe.'),
('10', 'Involve tend girl push professional wear network. Effort painting read identify for.'),
('9', 'Probably none offer. Join lead able occur bad design ground.'),
('19', 'Push but ability offer people where think ever. Tv compare provide most analysis.'),
('2', 'Evening religious budget oil professor decade budget.'),
('21', 'Form discussion marriage travel last center choose reveal.'),
('13', 'Detail indeed involve loss. If sit box work field.'),
('3', 'Building which identify society marriage computer quite.'),
('20', 'Without evidence usually she kind add impact. Candidate officer right front key the agent after.'),     
('15', 'Out product vote professional sing research build. Fall news tonight would.'),
('36', 'Which peace weight less by several head. Throw sure fund language.'),
('15', 'International have tax company discover eight certain.'),
('20', 'Deal our smile author term environmental various back. Dream thousand draw pick people real.'),
('11', 'Week make group building alone spring happen them.'),
('21', 'Itself build between character message tax pass. Check by state.');

-- Scenario Practice Data
INSERT INTO scenario_practice VALUES
('17', 'Must short different however hand.', 'Fluent'),
('3', 'From both finish. Again scientist eight should.', 'Advanced'),
('25', 'Pick capital industry travel not say.', 'Intermediate'),
('17', 'Increase now people.', 'Fluent'),
('22', 'Catch environmental future class important party.', 'Intermediate'),
('24', 'Action use also air modern act without home.', 'Fluent'),
('1', 'Or reality already seek couple choose room.', 'Advanced'),
('18', 'Stock miss lose phone.', 'Fluent'),
('36', 'Give put risk cell tree bill night.', 'Advanced'),
('31', 'Use authority writer activity some woman quite.', 'Intermediate'),
('10', 'Good quite student movie when rather.', 'Fluent'),
('13', 'Suffer newspaper outside protect.', 'Intermediate'),
('30', 'About human worry blood remember no send.', 'Beginner'),
('20', 'Action kid money without understand.', 'Intermediate'),
('4', 'If reality be old off day ahead.', 'Advanced'),
('12', 'Those consumer shake support about.', 'Intermediate'),
('36', 'Laugh anyone easy green could.', 'Intermediate'),
('8', 'Door child east official media market.', 'Beginner'),
('34', 'Night number poor sit born.', 'Advanced'),
('23', 'Position rather onto. Throw action cover.', 'Advanced'),
('31', 'Exist suggest peace according ground identify.', 'Intermediate'),
('19', 'Management full modern on music woman.', 'Fluent'),
('30', 'Them gas rich exactly would draw anything.', 'Fluent'),
('9', 'Little will season concern floor.', 'Advanced'),
('39', 'Father enter sometimes guess positive size.', 'Fluent'),
('14', 'Believe play summer letter hour new anything.', 'Intermediate'),
('7', 'Take make sing affect cost wonder evening moment.', 'Fluent'),
('3', 'Theory break use opportunity none.', 'Beginner'),
('26', 'Authority value federal address sing she ago.', 'Intermediate'),
('10', 'Road rise build order commercial beautiful.', 'Intermediate'),
('3', 'Skin type when nothing.', 'Beginner'),
('39', 'Begin each teacher address research mean light.', 'Intermediate'),
('39', 'House face effort understand hot all he continue.', 'Beginner'),
('37', 'Eat century second hour miss man summer but.', 'Beginner'),
('4', 'Room second put mother security call body toward.', 'Intermediate'),
('12', 'Important growth should end suffer we.', 'Beginner'),
('36', 'Program matter agent many religious teach.', 'Beginner'),
('8', 'Election mouth speech memory.', 'Fluent'),
('8', 'Be election stop baby baby.', 'Intermediate'),
('11', 'Fact provide industry theory.', 'Fluent');

-- Vocabulary Practice Data
INSERT INTO vocab_practice VALUES
('25', 'Rest significant late report.', 'Fluent'),
('21', 'Instead board institution top owner.', 'Intermediate'),
('23', 'Heart hear sense top. We matter size spring.', 'Advanced'),
('35', 'Us house green really.', 'Fluent'),
('5', 'Mr pass such life.', 'Intermediate'),
('29', 'Position politics forget real election check.', 'Advanced'),
('8', 'Goal discover teach argue rate admit.', 'Intermediate'),
('25', 'Choice wear can study sign.', 'Fluent'),
('21', 'Future big become day.', 'Advanced'),
('31', 'Whether seek compare nation.', 'Advanced'),
('11', 'City lose contain hour with.', 'Advanced'),
('12', 'Despite anything itself court space artist.', 'Beginner'),
('32', 'Traditional team interesting across must peace.', 'Intermediate'),
('6', 'Least let agent simply difficult.', 'Fluent'),
('2', 'Beyond score move wrong part.', 'Beginner'),
('32', 'Election specific general however consider eye.', 'Fluent'),
('21', 'Check do specific story sometimes.', 'Fluent'),
('30', 'Once whole ask team.', 'Advanced'),
('36', 'Evening development return assume center.', 'Beginner'),
('12', 'Several foreign want box.', 'Fluent'),
('8', 'Candidate drop number drive wonder myself turn.', 'Fluent'),
('29', 'Outside type low cell town our teach.', 'Fluent'),
('10', 'Safe long contain Mrs wrong day upon operation.', 'Beginner'),
('35', 'Moment population because investment main.', 'Beginner'),
('26', 'Short real point school finally.', 'Advanced'),
('5', 'Modern image any save firm purpose voice.', 'Fluent'),
('14', 'Much assume movement wear while test power.', 'Intermediate'),
('37', 'Strategy allow rest what put mention.', 'Intermediate'),
('22', 'Claim despite affect.', 'Intermediate'),
('26', 'Month serve public admit.', 'Beginner'),
('18', 'Grow practice I every bag.', 'Advanced'),
('39', 'Lay report space two identify include research.', 'Advanced'),
('39', 'Human country factor during war.', 'Advanced'),
('1', 'Treatment popular stop.', 'Beginner'),
('3', 'Box give job station.', 'Intermediate'),
('25', 'Dinner allow similar air.', 'Fluent'),
('23', 'Far reveal thought American hard shoulder.', 'Intermediate'),
('25', 'Market affect ask country oil.', 'Intermediate'),
('13', 'Down by talk ask break.', 'Beginner'),
('11', 'Occur trial town involve.', 'Fluent');
PS C:\Users\arnav\Documents\GitHub\BARBARIAN-GLOBAL-CONNECT> & C:/Users/arnav/anaconda3/python.exe c:/Users/arnav/Documents/GitHub/BARBARIAN-GLOBAL-CONNECT/api/backend/sample_data.py
-- System Administrator Data
INSERT INTO system_administrator VALUES
('smoreno@example.com', 'Russell', 'Moore', 'Content Manager'),
('nlynn@example.com', 'Jimmy', 'Ramirez', 'System Admin'),
('erik88@example.net', 'Amanda', 'Jenkins', 'Content Manager'),
('christophermay@example.org', 'Jacob', 'Brennan', 'System Admin'),
('jwhite@example.org', 'William', 'May', 'Content Manager'),
('stephen23@example.net', 'Brianna', 'Carlson', 'Content Manager'),
('brandyestes@example.org', 'Kyle', 'Hill', 'System Admin'),
('tracy14@example.net', 'Tony', 'Harris', 'Support Specialist'),
('justinflynn@example.com', 'Angel', 'Johnson', 'Content Manager'),
('christopherjohns@example.com', 'Erin', 'Herrera', 'Support Specialist');

-- Mentee Data
INSERT INTO mentee VALUES
('9', '4', 'Mark', 'Morris', 'ohumphrey@example.com', 'French', 'Fluent'),
('5', '10', 'Kelly', 'Smith', 'patelsamantha@example.net', 'Spanish', 'Beginner'),
('2', '7', 'Shane', 'Rojas', 'jeremiah55@example.com', 'Spanish', 'Beginner'),
('2', '8', 'Kristen', 'Shaffer', 'annewagner@example.com', 'French', 'Advanced'),
('7', '9', 'Sara', 'Frazier', 'michelle60@example.com', 'Japanese', 'Fluent'),
('10', '6', 'Sydney', 'Warren', 'wendyarellano@example.org', 'Japanese', 'Fluent'),
('3', '2', 'William', 'Lowe', 'brandon69@example.com', 'French', 'Advanced'),
('4', '10', 'Dalton', 'Gray', 'thomassmith@example.com', 'Chinese', 'Beginner'),
('3', '2', 'Marcus', 'Miller', 'stacyprice@example.net', 'Japanese', 'Beginner'),
('3', '9', 'Richard', 'Mitchell', 'lisa41@example.com', 'Spanish', 'Advanced'),
('9', '3', 'Michael', 'Cobb', 'ronaldmontoya@example.net', 'Japanese', 'Advanced'),
('9', '6', 'Rebecca', 'Moore', 'patrick78@example.net', 'Chinese', 'Intermediate'),
('1', '5', 'Morgan', 'Brooks', 'orodriguez@example.org', 'Spanish', 'Beginner'),
('2', '5', 'Bobby', 'Stewart', 'brewerkenneth@example.net', 'Japanese', 'Fluent'),
('9', '8', 'Susan', 'Lopez', 'tylerdavidson@example.com', 'Japanese', 'Beginner'),
('10', '10', 'April', 'Anderson', 'laurie54@example.net', 'Japanese', 'Beginner'),
('1', '5', 'Karina', 'Murphy', 'bonnie87@example.com', 'Spanish', 'Beginner'),
('6', '2', 'Ian', 'Palmer', 'andrew07@example.net', 'Chinese', 'Fluent'),
('6', '10', 'Amanda', 'Dyer', 'savannah42@example.net', 'Chinese', 'Fluent'),
('6', '5', 'Courtney', 'Weber', 'murraykenneth@example.net', 'French', 'Intermediate'),
('3', '4', 'Susan', 'Cox', 'yvonnesmith@example.org', 'Spanish', 'Beginner'),
('6', '7', 'Francis', 'Trujillo', 'edwinmoore@example.net', 'French', 'Intermediate'),
('1', '10', 'Heather', 'Sandoval', 'daniel40@example.net', 'Spanish', 'Advanced'),
('8', '8', 'Adam', 'Casey', 'gblack@example.net', 'Spanish', 'Beginner'),
('5', '3', 'Erik', 'Jackson', 'anthonyjamie@example.org', 'French', 'Intermediate'),
('3', '1', 'Timothy', 'Gomez', 'millerjennifer@example.org', 'Spanish', 'Fluent'),
('8', '3', 'Dominique', 'Williams', 'sharon30@example.com', 'Japanese', 'Advanced'),
('1', '5', 'Alexa', 'Alvarez', 'adamsbarbara@example.com', 'Spanish', 'Advanced'),
('5', '10', 'Bryan', 'Delgado', 'morgan59@example.com', 'Chinese', 'Advanced'),
('7', '2', 'Jill', 'Jones', 'amyjohnson@example.com', 'Spanish', 'Intermediate'),
('2', '9', 'Rebecca', 'Garrett', 'eclay@example.net', 'Chinese', 'Beginner'),
('7', '9', 'Erica', 'Reid', 'george48@example.org', 'Japanese', 'Beginner'),
('7', '9', 'Laura', 'Brown', 'samantha00@example.com', 'Spanish', 'Advanced'),
('2', '8', 'Jonathan', 'Parker', 'robertsrachel@example.net', 'French', 'Advanced'),
('7', '7', 'Michael', 'Le', 'robin21@example.org', 'French', 'Intermediate'),
('4', '2', 'Derek', 'Johnson', 'mvargas@example.net', 'French', 'Fluent'),
('3', '2', 'Michael', 'Wright', 'sarawilson@example.com', 'Chinese', 'Beginner'),
('8', '8', 'Crystal', 'Ross', 'jeanette39@example.org', 'Spanish', 'Beginner'),
('1', '6', 'Lori', 'Wright', 'davisjoseph@example.org', 'Japanese', 'Beginner'),
('2', '10', 'Ashley', 'Lopez', 'hayley01@example.org', 'French', 'Intermediate');

-- Mentor Data
INSERT INTO mentor VALUES
('5', '3', 'Casey', 'Pugh', 'lperez@example.net', 'French', 'North Becky, Italy', 'Advanced'),
('7', '10', 'Patty', 'Anderson', 'vasquezjoshua@example.net', 'Japanese', 'Yolandafort, Ukraine', 'Advanced'),  
('8', '9', 'Felicia', 'Miles', 'margaretkeller@example.org', 'French', 'Melissaville, Nauru', 'Advanced'),      
('7', '7', 'Miguel', 'Hess', 'ivalenzuela@example.net', 'Spanish', 'New Malik, Luxembourg', 'Advanced'),        
('2', '8', 'Valerie', 'Herrera', 'michele25@example.net', 'Japanese', 'Reyesshire, Uganda', 'Fluent'),
('7', '3', 'George', 'Young', 'scott03@example.org', 'Japanese', 'Harmonhaven, Jersey', 'Advanced'),
('1', '10', 'Michele', 'Bass', 'donnaholloway@example.org', 'Chinese', 'Richardmouth, Lesotho', 'Fluent'),      
('2', '8', 'Eric', 'Hayes', 'ptaylor@example.net', 'Chinese', 'New Nancy, Aruba', 'Advanced'),
('4', '4', 'Mary', 'Hartman', 'melissa47@example.net', 'Chinese', 'New Jaredtown, Grenada', 'Advanced'),        
('4', '10', 'Jason', 'Kennedy', 'edward76@example.org', 'Spanish', 'Taylorfort, Suriname', 'Advanced');

-- Learning Path Data
INSERT INTO learning_path VALUES
('31', '8', 'Module 1', 'Avoid example trial now increase.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('37', '10', 'Module 4', 'Rest likely under group.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),      
('7', '10', 'Module 2', 'Training no win hotel.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),      
('2', '8', 'Module 2', 'Former letter physical for popular floor right.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('2', '5', 'Module 3', 'Notice remember just few cell. Only fund public.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('10', '3', 'Module 3', 'Mrs PM room blood.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('3', '3', 'Module 4', 'Door down future site walk note bill.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),
('40', '9', 'Module 4', 'Meeting fall book traditional. Worry home sea.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('4', '6', 'Module 3', 'Use cause just why ground read.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),     
('24', '8', 'Module 4', 'Pass he me yard stock history.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),     
('14', '2', 'Module 4', 'Activity soon machine safe discover smile.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('2', '7', 'Module 2', 'Team over good blood note.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),     
('9', '9', 'Module 2', 'Baby agent financial always.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),        
('10', '7', 'Module 3', 'And address contain skill.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),    
('5', '8', 'Module 2', 'Whose town work where.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),       
('24', '5', 'Module 5', 'Whole whatever order eat.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),
('4', '7', 'Module 2', 'Grow fight discussion ground teacher various.', 'Milestone 1, Milestone 2, Milestone 3', 'Pending'),
('13', '7', 'Module 1', 'Majority specific exactly probably.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),
('30', '4', 'Module 2', 'Close center each pattern key mention.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('5', '1', 'Module 4', 'Care imagine past.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('10', '10', 'Module 1', 'Information hospital staff century.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('11', '6', 'Module 1', 'Budget personal child city industry.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('22', '6', 'Module 3', 'Table few behavior past.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),      
('32', '8', 'Module 4', 'Later thought soldier buy both one.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('14', '9', 'Module 4', 'Word management nothing president seek authority.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('28', '9', 'Module 2', 'Final house maintain Democrat sister such arm.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),
('8', '6', 'Module 5', 'Call right radio. Whether few half relate.', 'Milestone 1, Milestone 2, Milestone 3', 'Pending'),
('34', '7', 'Module 2', 'Up far piece tree must hospital.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('13', '6', 'Module 2', 'Wind growth show perhaps everyone direction.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('37', '10', 'Module 2', 'Matter contain charge standard. Care talk close.', 'Milestone 1, Milestone 2, Milestone 3', 'Pending'),
('17', '5', 'Module 5', 'Appear establish hour adult.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),   
('13', '8', 'Module 1', 'Team appear now. Interest argue whole head.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),
('15', '7', 'Module 3', 'Doctor front institution.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),     
('26', '8', 'Module 1', 'Deep answer glass call in check.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('35', '7', 'Module 5', 'Artist strong film writer. Concern billion claim.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('35', '8', 'Module 3', 'Far herself nice price energy industry.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('10', '7', 'Module 4', 'Still strong reveal responsibility.', 'Milestone 1, Milestone 2, Milestone 3', 'Pending'),
('1', '5', 'Module 5', 'Agreement clearly owner four glass draw.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('17', '5', 'Module 5', 'Direction away probably skin skill.', 'Milestone 1, Milestone 2, Milestone 3', 'Pending'),
('12', '3', 'Module 1', 'Shake financial case week hope different cost.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started');

-- Progress Data
INSERT INTO progress VALUES
('14', '35', 'Not Started', '2024-03-09'),
('13', '12', 'Resolved', '2024-04-26'),
('27', '7', 'Not Started', NULL),
('2', '23', 'Open', '2024-03-08'),
('2', '6', 'Completed', '2024-11-11'),
('33', '31', 'In Progress', NULL),
('11', '13', 'Pending', '2024-08-23'),
('17', '17', 'Pending', '2024-05-13'),
('35', '28', 'In Progress', '2024-02-27'),
('5', '40', 'Resolved', NULL),
('26', '36', 'Resolved', '2024-04-12'),
('16', '17', 'In Progress', NULL),
('26', '30', 'Open', '2024-04-15'),
('19', '39', 'In Progress', '2024-03-03'),
('12', '37', 'Not Started', '2024-05-28'),
('17', '27', 'Pending', '2024-03-05'),
('28', '21', 'Pending', NULL),
('21', '23', 'Resolved', '2024-12-01'),
('27', '23', 'Pending', '2024-11-22'),
('3', '40', 'Resolved', '2024-06-07'),
('22', '18', 'Completed', NULL),
('21', '15', 'Not Started', '2024-11-12'),
('34', '38', 'In Progress', '2024-06-16'),
('2', '2', 'In Progress', '2024-08-20'),
('30', '31', 'Completed', '2024-07-04'),
('19', '31', 'Not Started', '2024-08-28'),
('14', '24', 'Resolved', '2024-02-17'),
('7', '2', 'Pending', NULL),
('4', '38', 'Not Started', '2024-06-10'),
('23', '6', 'In Progress', NULL),
('14', '40', 'Open', '2024-09-01'),
('22', '11', 'Open', NULL),
('24', '24', 'Open', '2024-02-07'),
('21', '29', 'In Progress', '2024-07-27'),
('9', '8', 'Completed', NULL),
('18', '4', 'Completed', '2024-07-19'),
('19', '9', 'Open', '2024-04-18'),
('38', '6', 'In Progress', '2024-06-18'),
('12', '10', 'Resolved', '2024-10-31'),
('39', '36', 'Not Started', '2024-11-17');

-- Issue Report Data
INSERT INTO issue_report VALUES
('27', '6', 'Resolved', 'Represent threat once watch. Gas relationship ability range arm.'),
('39', NULL, 'Open', 'Figure soon method will necessary ten. Season town blue term everything now.'),
('14', '1', 'Not Started', 'Report main quite experience. Ten economic along because point again.'),
('40', '2', 'Resolved', 'Mean program step team road look leg. Growth discussion debate one.'),
('4', '2', 'Open', 'Easy group short effect practice bill. Physical decide someone miss state door try.'),      
('12', NULL, 'Open', 'Value firm food. Account morning report within pay.'),
('4', '7', 'Completed', 'Each ago could father meet exactly policy.'),
('36', '5', 'Completed', 'Citizen although seem meet. Wall friend leave skill later avoid. Really explain our former away.'),
('15', '8', 'In Progress', 'Actually my here water.
Term material serve son effect. Place money scene law.'),
('21', '10', 'In Progress', 'Throughout themselves now remain. Consumer make that interview ever.'),
('5', '7', 'Completed', 'Interview bar take reality course. Company factor challenge name really parent price.'),
('15', '1', 'Completed', 'Question instead seat born. Letter same effort create.'),
('19', NULL, 'Resolved', 'Teach agree always. Factor note research trade push turn.'),
('30', NULL, 'Not Started', 'Term likely go one. Crime son Democrat.'),
('16', NULL, 'Open', 'Late return production. Individual glass air tonight.
Magazine school thousand cultural form son.'),
('38', '7', 'Completed', 'Quite always major really. Stay ok improve community everyone enjoy.'),
('32', '10', 'In Progress', 'Over today tax gas. Name cup with tree however you.'),
('23', '9', 'In Progress', 'Laugh his financial sometimes both. Stage nor various word level whom. Hard kid question drug.'),
('39', '7', 'In Progress', 'Up window west ability.'),
('16', '6', 'Completed', 'Discussion we class war.
Amount top yeah way. Across behavior make general travel take heart.'),
('15', '4', 'Resolved', 'Doctor action perform market mention identify officer. Require each factor bring.'),   
('11', '8', 'Pending', 'History player arm thing. Child reality their up over others better.'),
('18', '5', 'Pending', 'Article article draw issue forward line detail. Bill form reflect democratic study.'),  
('38', NULL, 'Not Started', 'Technology yourself budget arrive. He administration father glass. Yourself customer everybody.'),
('21', NULL, 'Completed', 'Far cut option understand. Whole investment pay event senior. Why able instead occur offer catch.'),
('26', NULL, 'In Progress', 'Before evidence eight investment which. Street offer else general.'),
('30', '9', 'In Progress', 'Ok always use range week. How suffer management by station. Outside current half method.'),
('20', '5', 'In Progress', 'Brother partner beat several plan heavy last. Miss whatever like. Full way up.'),   
('21', '6', 'In Progress', 'Wall also bring use apply cause statement. Tonight age southern suffer.'),
('36', NULL, 'Not Started', 'Pull whole six image along. Crime year must tonight focus. Attorney should rest industry.'),
('15', '1', 'In Progress', 'By save TV worry control safe. Show democratic under strategy sport project.'),     
('35', '3', 'Not Started', 'Alone country matter dinner help point themselves. Myself business garden usually fill her same.'),
('29', '5', 'Not Started', 'Might window cover list. End red beat. Thank leg later seat.'),
('19', NULL, 'In Progress', 'Continue game they. Reality some use or body.'),
('28', NULL, 'Not Started', 'Only it stage already. Amount number become total. Side seat often friend large.'),
('39', '8', 'Completed', 'Drop war yard response really. Sell book every join laugh maintain executive city.'), 
('22', NULL, 'Pending', 'Go however story floor. Stay behavior have chance both direction. Minute cup yard right simple on.'),
('16', '9', 'Completed', 'Sometimes rate perhaps here determine start. Make whatever major place quite.'),      
('38', NULL, 'Open', 'Bank business huge always pull voice. Free boy bit how himself us. Edge care own ago.'),  
('23', '2', 'Resolved', 'Find maintain training difficult. From dog everything herself against room network.'); 

-- Content Updates Data
INSERT INTO content_updates VALUES
('22', '9', 'Cell war drop will happy senior.'),
('6', '7', 'Carry south manager charge special. Personal high less bank can ago.'),
('10', '3', 'Family hold itself friend remember provide. Seat discuss party he huge.'),
('16', '6', 'Goal collection forward national economy training situation. Direction consumer even if set.'),    
('5', '7', 'Focus hear treat agreement animal friend. Apply interest ready before include popular much.'),      
('9', '1', 'Join receive science.
Moment he these set camera. Cause suffer morning news who bill rest.'),
('22', '4', 'Generation health similar off. Newspaper near itself nation view result chair.'),
('8', '4', 'Sell air store. Form company imagine right.'),
('24', '2', 'Whether quite number accept consumer real. International cause someone quickly real Mrs same.'),   
('19', '6', 'Everything miss list. Religious deep half window woman. Property approach beyond begin.'),
('34', '6', 'Present race ready what.'),
('12', '1', 'Property collection most these. Which local surface do what well expect.'),
('37', '9', 'Learn either maintain bill himself. Until water how produce natural effort.'),
('1', '10', 'Traditional cause whatever summer central hit leave.'),
('26', '6', 'Sense politics hotel box. Lose board evidence tree fine.'),
('28', '7', 'Sort exactly gas mother girl each picture week.'),
('25', '1', 'Pattern trial offer cold similar life south.
Against top expect break actually positive individual.'),
('22', '6', 'Major police watch. Along wind officer sure institution use. Bring foreign involve look.'),        
('17', '9', 'House step option want consumer ground. Modern allow together beautiful.'),
('25', '2', 'Trial sense end whatever. Any thought provide manager force. Edge pick nature.'),
('25', '4', 'Several sing star political. News computer think home.
Look free address first phone half Mr.'),
('28', '8', 'Kitchen always subject. Event southern institution director interest above. Medical forget citizen.'),
('25', '2', 'Customer goal guy hour history affect. Be never door window we wide.'),
('25', '2', 'Month kid arrive. Choose question service clearly money land. Gun conference that research economy.'),
('21', '8', 'Stop where learn brother partner rock happy. Per what today discuss support church.'),
('18', '10', 'Likely author large response.'),
('30', '5', 'Always focus every visit hospital debate. From more visit production.'),
('19', '4', 'Read official life new particular family.'),
('8', '8', 'Seek church easy each know kind leg. Yes goal opportunity Congress court direction why.'),
('15', '5', 'Director shake reduce product agent car. Everybody we off may campaign. Smile include employee.'), 
('21', '9', 'Rate itself line country western. Will above participant difference church exactly.'),
('21', '3', 'What need evening low prove. System deal interview most.'),
('3', '4', 'Big card respond. She majority may voice.'),
('24', '7', 'Report since fine realize authority deep. Significant pay near nice religious option season.'),    
('30', '1', 'Must remain design win. His staff she watch. Foreign control sign medical.'),
('16', '1', 'Education weight only police man money. Visit bank view sound among travel issue.'),
('28', '10', 'Couple talk ahead win fast traditional. Pass during against especially.'),
('21', '8', 'Able rich list. Ready Republican word responsibility year necessary. Sure compare oil former.'),   
('5', '5', 'Detail long wonder goal government improve wear. Visit difference manager us add.'),
('6', '10', 'Stock down section detail. Teach approach mouth budget.');

-- Session Data
INSERT INTO session VALUES
('10', '6', 'Miss half military strong.', '2024-06-22', '02:41:00'),
('27', '4', 'Thought force nothing task create.', '2024-02-10', '01:00:00'),
('36', '6', 'Fall city become group determine election.', '2024-11-04', '01:21:00'),
('30', '1', 'Federal allow decade treatment like with.', '2024-08-23', '00:14:00'),
('36', '9', 'Get policy note soon. Resource talk blue.', '2024-03-08', '01:44:00'),
('3', '5', 'Listen green he food push during present.', '2024-12-01', '02:19:00'),
('1', '2', 'Already account us analysis.', '2024-10-24', '01:48:00'),
('27', '8', 'Social card physical simply north.', '2023-12-17', '03:37:00'),
('38', '10', 'Door always until owner peace. One drop three.', '2024-09-18', '03:16:00'),
('37', '10', 'Popular course head on determine.', '2024-05-03', '02:28:00'),
('3', '1', 'Dark central some wind question.', '2024-04-24', '02:11:00'),
('6', '2', 'Choice measure why new.', '2024-10-17', '03:01:00'),
('4', '5', 'Pull audience state pressure.', '2024-11-14', '03:01:00'),
('37', '8', 'Information great reach pay way.', '2024-08-19', '00:26:00'),
('4', '3', 'Success commercial do run.', '2024-10-03', '02:17:00'),
('39', '1', 'Glass everything approach poor set.', '2024-08-01', '02:55:00'),
('40', '6', 'Bad professor recent receive.', '2024-07-16', '03:35:00'),
('14', '4', 'Their important capital break receive vote.', '2024-07-29', '03:36:00'),
('33', '1', 'Week son plant hope power.', '2024-03-10', '02:10:00'),
('8', '4', 'Show us guy.', '2024-03-17', '03:26:00'),
('11', '3', 'Trip plan product ability.', '2024-03-29', '02:15:00'),
('40', '6', 'There do gas of above sing free.', '2024-07-24', '03:01:00'),
('14', '10', 'Occur question base go include.', '2024-01-17', '01:09:00'),
('14', '9', 'Tax strong traditional notice. Poor memory wish.', '2024-09-05', '02:11:00'),
('20', '1', 'Like guy mission whole exist less.', '2024-07-04', '00:09:00'),
('39', '1', 'Lose night trial read understand fly agent by.', '2024-06-26', '03:53:00'),
('12', '7', 'My million education human.', '2024-05-30', '01:39:00'),
('31', '8', 'World yet run. Director red pull campaign couple.', '2024-03-20', '02:49:00'),
('15', '8', 'News company almost court smile although forget.', '2024-02-18', '02:57:00'),
('3', '4', 'Small memory simply democratic hard.', '2024-03-24', '01:40:00'),
('4', '6', 'System late seek inside manager everybody cause.', '2024-02-16', '01:37:00'),
('13', '6', 'Read oil piece. Scientist huge memory seat.', '2024-09-05', '02:06:00'),
('17', '5', 'Life little program car course wait.', '2024-11-08', '01:50:00'),
('15', '1', 'Write story development once hair write.', '2023-12-06', '02:57:00'),
('10', '9', 'Bad gas wall position writer development safe.', '2024-04-06', '01:00:00'),
('26', '4', 'Memory city eight owner indeed draw money.', '2024-05-09', '02:19:00'),
('29', '8', 'Third sit technology artist west set each.', '2024-09-16', '02:11:00'),
('17', '4', 'Face present ok civil nice image strong.', '2024-01-29', '00:36:00'),
('33', '5', 'Race parent per allow never bed until.', '2024-09-24', '01:26:00'),
('4', '4', 'Direction end enter guy. Collection name five.', '2024-04-21', '03:03:00');

-- Feedback Data
INSERT INTO feedback VALUES
('9', 'Image cost themselves however face remain hit probably. Personal these pull. Fly not system single.'),   
('35', 'Mission happen toward ready friend develop. Image course rich program hope film operation.'),
('26', 'Wonder compare nothing administration or old state. Office tree down sit small me.'),
('23', 'Home event job from generation even. Onto physical very spend. Enough plant indicate public.'),
('34', 'Main cover increase hospital plant then young. Natural picture with identify.'),
('25', 'Account next force. Claim nice edge tough.'),
('15', 'Late possible whom tax camera director. Our personal shake owner.'),
('27', 'Program air bad whole. Degree similar young program.'),
('23', 'Once worry order information.'),
('6', 'Trade professional direction buy.'),
('38', 'Specific our continue. Market past deep music half important. A action prove large out.'),
('21', 'Real human single artist watch theory. Certain enough whose politics.'),
('35', 'Speak away throughout point fight agency. Tend particular ball close effort bank practice.'),
('30', 'Movement project clearly pick. Win participant moment.'),
('28', 'Author box even house performance tax front poor. Large door current full candidate throw.'),
('27', 'Message if such morning view. Economy both follow.'),
('13', 'Most popular develop turn also economy value. Free among open any course their modern.'),
('30', 'Bag standard democratic money. Add him strategy girl bring same do.'),
('26', 'Debate feel after need have area purpose. Respond medical health describe just people.'),
('20', 'Senior cost far contain develop. Believe office Mr space style difficult which.'),
('7', 'Source fight poor character else western turn tonight. Will type beyond choice area close.'),
('21', 'Since impact middle program season. Western it try worry push.'),
('17', 'Behind American difficult challenge. Item subject interview market girl hear movement.'),
('34', 'Country address nice better.
Value world participant. Movement low win training reach throw drop.'),
('20', 'Check yeah yourself bit relationship that response. Medical home little morning analysis.'),
('14', 'Race writer nor consider white bank among. Choice wrong man pressure condition chance blood amount.'),  
('20', 'All as wide store actually at. Loss course notice ball you these. Democrat term subject very draw.'),   
('38', 'Financial sea few big science usually. There answer central smile finally team.'),
('2', 'Live rise film born program.'),
('12', 'Wonder suffer so young condition popular tough. Should along parent way.'),
('35', 'Between recognize herself fill.'),
('6', 'Seat record finally. Artist sometimes improve act.'),
('15', 'Moment behavior represent capital.
Nearly little project then about pretty network school.'),
('30', 'Sister war dark.
Focus nation woman teach stock degree. Recognize forward my question American.'),
('4', 'I create happy once wonder article writer. Walk say size. Dog father find score of trip.'),
('38', 'Listen network drive second enter blood contain education. Number stock that machine suffer.'),
('11', 'Wide manage still official. Occur student science describe raise likely.'),
('18', 'Produce morning charge. Deal expert who really until early right. Go any specific.'),
('27', 'Form very travel deal politics deal. Player help authority mention director cold. Civil both very.'),   
('11', 'Little purpose say. Build box opportunity general create.');

-- Scenario Practice Data
INSERT INTO scenario_practice VALUES
('23', 'Little set road participant.', 'Beginner'),
('12', 'Whole others always.', 'Beginner'),
('24', 'Close month hand accept probably.', 'Fluent'),
('4', 'Walk whatever speech stage.', 'Fluent'),
('27', 'Arrive admit because attention kid.', 'Advanced'),
('1', 'Sign student manager whatever.', 'Beginner'),
('6', 'Meet fall visit threat do.', 'Intermediate'),
('16', 'Large between reveal answer.', 'Advanced'),
('36', 'Interview area his skin rate fine former.', 'Advanced'),
('32', 'Forward man summer house join senior key among.', 'Fluent'),
('10', 'Throw population main game whole son.', 'Advanced'),
('9', 'Especially go if customer major.', 'Advanced'),
('24', 'Explain car question form expert kitchen.', 'Fluent'),
('21', 'Include bit owner them.', 'Intermediate'),
('11', 'Put process no report.', 'Intermediate'),
('19', 'Environment film probably school.', 'Beginner'),
('33', 'Least card computer once give.', 'Advanced'),
('40', 'Drop worry relate relate film.', 'Beginner'),
('4', 'However civil important nice pick some sometimes.', 'Intermediate'),
('24', 'Support home in political read inside.', 'Fluent'),
('40', 'Term cell avoid they citizen visit what run.', 'Intermediate'),
('8', 'National land money yard success wall art.', 'Beginner'),
('17', 'Available one and provide save evening half.', 'Beginner'),
('19', 'Manage why list half share focus morning.', 'Fluent'),
('9', 'How look you class. Avoid smile feel strategy.', 'Fluent'),
('29', 'Kitchen various language news imagine discover.', 'Fluent'),
('20', 'Local always everybody.', 'Advanced'),
('11', 'Discussion official after seat series.', 'Fluent'),
('38', 'Yard buy do official poor bill level trial.', 'Beginner'),
('9', 'Seem many clearly election money.', 'Fluent'),
('33', 'Another wear section care view.', 'Fluent'),
('31', 'Space weight present.', 'Beginner'),
('3', 'Red skin see than pass true.', 'Advanced'),
('32', 'Attorney much west indicate sell alone hope.', 'Advanced'),
('37', 'How guess car. Many should fear teach.', 'Fluent'),
('34', 'She role increase window.', 'Fluent'),
('17', 'Audience federal produce. Third long color low.', 'Beginner'),
('39', 'Always act lawyer talk.', 'Beginner'),
('31', 'Rather tell support ever central.', 'Intermediate'),
('29', 'System expert few something prove they yard.', 'Fluent');

-- Vocabulary Practice Data
INSERT INTO vocab_practice VALUES
('13', 'Work task society discussion.', 'Fluent'),
('31', 'Open opportunity site hard.', 'Fluent'),
('20', 'Seat win commercial safe wind.', 'Intermediate'),
('29', 'Personal movement chair adult foreign bad entire.', 'Intermediate'),
('18', 'Party return tell if property place.', 'Fluent'),
('26', 'Recent reality town important thank likely them.', 'Fluent'),
('16', 'Pm spring speak unit staff condition instead.', 'Fluent'),
('3', 'Use important industry agreement son.', 'Advanced'),
('34', 'Other chance American.', 'Fluent'),
('38', 'Follow half free peace would car.', 'Advanced'),
('15', 'She yard remember sea.', 'Fluent'),
('30', 'Should something sort.', 'Fluent'),
('10', 'Life growth ask night capital.', 'Intermediate'),
('1', 'Enter lose side act.', 'Advanced'),
('37', 'Rate loss past Mrs contain.', 'Beginner'),
('6', 'Whom rich social factor.', 'Fluent'),
('33', 'Off job sort identify.', 'Advanced'),
('32', 'Cut service painting.', 'Intermediate'),
('18', 'Tend glass nothing chair.', 'Intermediate'),
('4', 'Several nation use information.', 'Intermediate'),
('16', 'Alone nearly amount vote check behavior.', 'Advanced'),
('8', 'How however treatment property upon real.', 'Fluent'),
('9', 'Old sometimes final financial research.', 'Fluent'),
('23', 'Good along night we. Movie must course surface.', 'Beginner'),
('38', 'National anything sport with sign while once.', 'Fluent'),
('40', 'Sound seven tree.', 'Beginner'),
('21', 'Environment star whether yeah decision.', 'Beginner'),
('39', 'Strategy international serve.', 'Intermediate'),
('2', 'Water field way east executive.', 'Intermediate'),
('39', 'Top strategy lot method music.', 'Beginner'),
('2', 'Reality without provide team to form.', 'Advanced'),
('25', 'Ask election interview finish.', 'Fluent'),
('33', 'Recently later require pretty forget policy fine.', 'Beginner'),
('15', 'Course including news itself.', 'Intermediate'),
('5', 'Arm its expect toward listen today.', 'Beginner'),
('6', 'Little unit dog attack see significant total.', 'Beginner'),
('9', 'Phone contain pay official school.', 'Beginner'),
('29', 'Even choose would it direction.', 'Advanced'),
('21', 'North bad decision include side work as.', 'Beginner'),
('7', 'Conference free appear your company cost.', 'Intermediate');