use global;

INSERT INTO system_administrator
VALUES
('brooke32@example.net', 'Donald', 'Campbell', 'Support Specialist'),
('melissamoore@example.com', 'Paul', 'Andrews', 'Content Manager'),
('blivingston@example.org', 'Megan', 'Murphy', 'Content Manager'),
('brianlee@example.net', 'Eugene', 'Harmon', 'Content Manager'),
('deniseanderson@example.org', 'Katherine', 'Mckay', 'Support Specialist'),
('wmichael@example.org', 'Ronald', 'Mathis', 'Content Manager'),
('andersoncarol@example.com', 'Joseph', 'Alvarez', 'Content Manager'),
('delgadochristina@example.net', 'Troy', 'Le', 'Content Manager'),
('michael37@example.net', 'Roger', 'Parker', 'Support Specialist'),
('simonandrew@example.net', 'Patricia', 'Carrillo', 'Support Specialist');

-- Mentee Data
INSERT INTO mentee
VALUES
('8', '10', 'Martin', 'Hill', 'madeline43@example.net', 'French', 'Beginner'),
('2', '10', 'Brenda', 'Jensen', 'davidtodd@example.org', 'Japanese', 'Beginner'),
('4', '8', 'Madison', 'Young', 'amanda24@example.net', 'Spanish', 'Beginner'),
('7', '10', 'Jim', 'Aguilar', 'mfarmer@example.com', 'Chinese', 'Beginner'),
('6', '10', 'Matthew', 'Baker', 'plyons@example.com', 'Chinese', 'Intermediate'),
('10', '8', 'Alisha', 'Frank', 'petersonjennifer@example.org', 'Chinese', 'Intermediate'),
('3', '6', 'Joshua', 'Gallegos', 'davidsonryan@example.com', 'French', 'Intermediate'),
('7', '8', 'Victoria', 'Sanders', 'jacksonamy@example.net', 'Chinese', 'Beginner'),
('6', '1', 'James', 'Patel', 'taylordrew@example.org', 'French', 'Advanced'),
('7', '7', 'Tracey', 'Camacho', 'ereilly@example.com', 'French', 'Fluent'),
('9', '2', 'Thomas', 'Smith', 'mfrederick@example.org', 'Spanish', 'Intermediate'),
('4', '1', 'Natalie', 'Poole', 'ksantiago@example.com', 'French', 'Intermediate'),
('10', '8', 'Chelsey', 'Nguyen', 'jody62@example.net', 'Chinese', 'Fluent'),
('5', '8', 'Chad', 'Hinton', 'froststuart@example.com', 'Japanese', 'Beginner'),
('8', '6', 'Donna', 'Crosby', 'davidflores@example.com', 'Spanish', 'Beginner'),
('5', '5', 'Amy', 'Scott', 'xkennedy@example.com', 'Spanish', 'Advanced'),
('3', '9', 'David', 'Nelson', 'andrea87@example.org', 'Spanish', 'Intermediate'),
('8', '6', 'Laura', 'Smith', 'david35@example.com', 'Chinese', 'Advanced'),
('3', '8', 'Christopher', 'Kramer', 'alleneric@example.org', 'French', 'Advanced'),
('10', '2', 'Elizabeth', 'Weaver', 'dylandavis@example.org', 'Chinese', 'Intermediate'),
('4', '4', 'Lisa', 'Padilla', 'dali@example.com', 'French', 'Intermediate'),
('3', '4', 'Christopher', 'Cochran', 'ztaylor@example.com', 'French', 'Intermediate'),
('7', '2', 'Daniel', 'Atkinson', 'pgarcia@example.net', 'Chinese', 'Beginner'),
('2', '1', 'Whitney', 'Hill', 'tranangela@example.com', 'Chinese', 'Fluent'),
('1', '9', 'Amanda', 'Garcia', 'kathleenhogan@example.net', 'Japanese', 'Fluent'),
('9', '2', 'Douglas', 'Lawrence', 'martingregory@example.net', 'French', 'Beginner'),
('10', '3', 'Luis', 'Manning', 'hineskathy@example.org', 'Chinese', 'Intermediate'),
('2', '8', 'Ann', 'Shah', 'hzhang@example.org', 'French', 'Beginner'),
('1', '2', 'Leah', 'Daniels', 'hgalvan@example.org', 'French', 'Intermediate'),
('1', '5', 'Justin', 'Johnson', 'ischwartz@example.org', 'French', 'Fluent'),
('3', '7', 'Evan', 'Mcdonald', 'paulallen@example.org', 'Spanish', 'Advanced'),
('10', '3', 'Jose', 'Decker', 'michael18@example.org', 'Japanese', 'Beginner'),
('3', '10', 'Taylor', 'Mora', 'adamlowe@example.org', 'Japanese', 'Fluent'),
('10', '2', 'James', 'Clark', 'kristen51@example.net', 'Spanish', 'Fluent'),
('5', '9', 'Anthony', 'Bell', 'susan08@example.com', 'Chinese', 'Fluent'),
('10', '10', 'Cassandra', 'Jarvis', 'ericward@example.org', 'Japanese', 'Advanced'),
('7', '3', 'Christine', 'Holt', 'dennisbarnes@example.net', 'Japanese', 'Beginner'),
('4', '3', 'Kelly', 'Gomez', 'haneydeborah@example.net', 'Spanish', 'Advanced'),
('7', '3', 'Joshua', 'Callahan', 'bhutchinson@example.com', 'French', 'Intermediate'),
('5', '8', 'Richard', 'Robinson', 'thomasmann@example.net', 'Chinese', 'Beginner');

-- Mentor Data
INSERT INTO mentor
VALUES
('6', '3', 'Ebony', 'Reed', 'abradshaw@example.com', 'Japanese', 'Tiffanyton, Guatemala', 'Fluent'),
('1', '1', 'Elaine', 'Miller', 'glennraymond@example.com', 'Japanese', 'Jamesville, Anguilla', 'Advanced'),
('6', '2', 'Jennifer', 'Rose', 'bakermiguel@example.com', 'French', 'Lake Nicolehaven, Cote dIvoire', 'Advanced'),
('9', '8', 'Derrick', 'Lopez', 'wanda64@example.org', 'Chinese', 'Lawsonhaven, Vietnam', 'Advanced'),
('1', '9', 'Kelly', 'White', 'michael43@example.org', 'Spanish', 'Turnerstad, Israel', 'Advanced'),
('6', '8', 'Sabrina', 'Becker', 'danielsrussell@example.net', 'Chinese', 'West Amy, Armenia', 'Fluent'),
('7', '5', 'Wanda', 'Hanson', 'earlnewton@example.com', 'Japanese', 'North Stephen, British Indian Ocean Territory (Chagos Archipelago)', 'Fluent'),
('6', '1', 'Cindy', 'Murray', 'briana26@example.com', 'Spanish', 'North Ronaldtown, Nepal', 'Advanced'),
('6', '6', 'April', 'Martinez', 'taylor38@example.org', 'Chinese', 'Jamesberg, Mauritius', 'Fluent'),
('9', '9', 'Mark', 'Webb', 'sschmidt@example.org', 'Spanish', 'Jenkinsview, Chile', 'Advanced'),
('7', '9', 'Thomas', 'Hansen', 'sramirez@example.com', 'Japanese', 'Port David, Sweden', 'Fluent'),
('4', '10', 'Joshua', 'Schwartz', 'riveramikayla@example.net', 'Spanish', 'Lake David, Bhutan', 'Advanced'),
('3', '7', 'Tanya', 'Green', 'abean@example.net', 'French', 'Mariastad, Liberia', 'Advanced'),
('9', '4', 'Nicholas', 'Perez', 'paulacain@example.com', 'Spanish', 'Rodriguezstad, Hong Kong', 'Advanced'),
('10', '3', 'Michael', 'Hopkins', 'sanchezapril@example.org', 'Spanish', 'South Todd, Lao Peoples Democratic Republic', 'Fluent'),
('6', '3', 'Sarah', 'Pearson', 'aingram@example.net', 'French', 'Jonathanfurt, Cape Verde', 'Fluent'),
('9', '8', 'Donna', 'Ingram', 'katiemay@example.org', 'French', 'Lake Marcusmouth, Korea', 'Advanced'),
('2', '8', 'Shannon', 'Ortega', 'pcooper@example.org', 'Japanese', 'East Blaketon, Cocos (Keeling) Islands', 'Fluent'),
('2', '7', 'Alec', 'Hodges', 'ulin@example.net', 'Spanish', 'Shepardton, Turkmenistan', 'Fluent'),
('8', '7', 'Henry', 'Wallace', 'jacobsthomas@example.net', 'Spanish', 'Murrayburgh, Togo', 'Fluent'),
('6', '5', 'Lisa', 'Castillo', 'richardblack@example.net', 'Chinese', 'East Patriciabury, Denmark', 'Fluent'),
('1', '1', 'Christine', 'Lewis', 'anewman@example.net', 'Spanish', 'Carlosview, Nauru', 'Advanced'),
('3', '3', 'Ashley', 'Gutierrez', 'daviscynthia@example.com', 'Spanish', 'East Richardmouth, Malaysia', 'Advanced'),
('6', '2', 'Jasmine', 'Jordan', 'julia36@example.org', 'Chinese', 'East Deborahland, Iran', 'Advanced'),
('10', '10', 'Teresa', 'Murphy', 'ograves@example.org', 'Japanese', 'Youngtown, Martinique', 'Advanced'),
('1', '8', 'Megan', 'Poole', 'edwardsedward@example.org', 'Japanese', 'South Tyler, Chad', 'Fluent'),
('8', '1', 'Scott', 'Baker', 'rarmstrong@example.org', 'Japanese', 'South Kimberly, Brazil', 'Advanced'),
('4', '10', 'Blake', 'Montgomery', 'phillipsthomas@example.org', 'Chinese', 'Danielleburgh, Saint Martin', 'Fluent'),
('2', '3', 'Lauren', 'Ward', 'thomas84@example.net', 'Spanish', 'Turnerport, Isle of Man', 'Fluent'),
('7', '7', 'Michael', 'Jimenez', 'navarrolinda@example.com', 'Chinese', 'New Julie, Dominica', 'Advanced'),
('9', '8', 'Victor', 'Swanson', 'fblack@example.com', 'French', 'Lake Jade, Reunion', 'Advanced'),
('9', '2', 'Nicholas', 'Dorsey', 'cummingsyolanda@example.net', 'Japanese', 'Gallagherberg, Bhutan', 'Fluent'),
('10', '4', 'Jeremy', 'Haney', 'clarkchristina@example.net', 'Chinese', 'South William, Albania', 'Fluent'),
('1', '4', 'Lauren', 'Garrison', 'lindsey06@example.com', 'Spanish', 'Garciachester, Turks and Caicos Islands', 'Advanced'),
('6', '4', 'James', 'Douglas', 'joshuamoore@example.net', 'Chinese', 'Erinchester, Paraguay', 'Advanced'),
('6', '4', 'Katelyn', 'Lewis', 'jacqueline63@example.org', 'French', 'Rebeccafort, China', 'Fluent'),
('9', '9', 'Kevin', 'Holmes', 'ashlee02@example.com', 'Chinese', 'Port Melissafort, Guinea-Bissau', 'Fluent'),
('4', '9', 'Thomas', 'Burch', 'sara43@example.org', 'French', 'Danside, Palau', 'Advanced'),
('6', '3', 'Anthony', 'Rivas', 'brendathomas@example.org', 'Spanish', 'South Barbara, Antigua and Barbuda', 'Fluent'),
('10', '7', 'Christopher', 'Monroe', 'perezdavid@example.org', 'French', 'North Margaret, Palau', 'Fluent');

-- Learning Path Data
INSERT INTO learning_path
VALUES
('40', '10', 'Module 1', 'Pressure name fall if line process.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('2', '1', 'Module 4', 'Last keep support ability beyond identify.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),
('11', '8', 'Module 4', 'Team pay test tell section try.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('3', '8', 'Module 3', 'Get decide already task smile Mrs power.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('6', '7', 'Module 2', 'Book enough friend.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),
('24', '8', 'Module 2', 'Fish send prepare benefit movie.', 'Milestone 1, Milestone 2, Milestone 3', 'Pending'),
('31', '5', 'Module 1', 'Face cold start church.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('35', '7', 'Module 1', 'Audience know pattern human.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),
('4', '3', 'Module 5', 'Without billion team our resource on window.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('19', '8', 'Module 2', 'Use represent fear.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('13', '5', 'Module 5', 'Similar research red now. Media popular above.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('34', '7', 'Module 3', 'Summer that value draw.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('20', '4', 'Module 4', 'His support article.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('27', '5', 'Module 3', 'Phone half when wish page.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),
('14', '4', 'Module 3', 'Travel poor though consumer.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('37', '10', 'Module 5', 'Should affect data company offer give piece.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('4', '10', 'Module 1', 'Analysis pick task likely.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('26', '5', 'Module 4', 'South story ask chair bad manager culture.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),
('17', '2', 'Module 3', 'Many mean they describe.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),
('22', '5', 'Module 5', 'Term radio pretty economic day now stay.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('28', '5', 'Module 4', 'White surface these against third turn.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),
('30', '1', 'Module 4', 'Face road cultural. Leg hair chair.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('32', '10', 'Module 1', 'Usually amount suffer end establish figure.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('33', '9', 'Module 3', 'Fine television share nearly main.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('24', '3', 'Module 4', 'Significant research raise information must.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('18', '7', 'Module 4', 'Hour product appear end player.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('6', '6', 'Module 3', 'Series song condition over debate name onto.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('40', '6', 'Module 5', 'Admit her his senior.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('31', '2', 'Module 1', 'Memory fact glass mission choice ability reason.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('6', '6', 'Module 5', 'Card cut model together about. Drug movie may in.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('14', '9', 'Module 1', 'These inside fact think stand.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('13', '6', 'Module 4', 'Difference food site article.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('6', '9', 'Module 5', 'Actually grow thousand body.', 'Milestone 1, Milestone 2, Milestone 3', 'Pending'),
('13', '2', 'Module 4', 'Song produce start artist worry woman.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('14', '1', 'Module 1', 'Other marriage brother carry stage speak.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),
('39', '6', 'Module 4', 'North middle prepare vote produce.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('9', '3', 'Module 3', 'Machine necessary hair control.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('8', '4', 'Module 4', 'For team part science group last.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('5', '5', 'Module 2', 'Fund do suggest beat.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('23', '2', 'Module 2', 'Maintain home move per teach ask population very.', 'Milestone 1, Milestone 2, Milestone 3', 'Open');

-- Progress Data
INSERT INTO progress
VALUES
('12', '18', 'Not Started', '2024-02-24'),
('11', '33', 'Open', '2024-05-08'),
('40', '17', 'Pending', '2024-05-27'),
('24', '7', 'Completed', '2024-01-17'),
('2', '23', 'Completed', '2024-11-13'),
('16', '31', 'Pending', NULL),
('40', '15', 'Not Started', NULL),
('22', '26', 'Pending', '2024-01-19'),
('13', '2', 'Pending', NULL),
('17', '10', 'Completed', NULL),
('3', '29', 'Not Started', '2024-06-16'),
('22', '9', 'Completed', NULL),
('11', '32', 'Not Started', '2024-09-23'),
('17', '3', 'Open', '2024-01-02'),
('7', '11', 'In Progress', NULL),
('2', '2', 'Open', NULL),
('26', '26', 'In Progress', '2024-09-18'),
('27', '23', 'Pending', NULL),
('31', '4', 'Completed', '2024-02-06'),
('8', '27', 'In Progress', '2024-01-27'),
('24', '6', 'Not Started', NULL),
('9', '6', 'Pending', '2024-04-17'),
('23', '4', 'In Progress', '2024-03-11'),
('8', '38', 'Open', '2024-07-15'),
('36', '36', 'Open', '2024-09-03'),
('30', '2', 'In Progress', NULL),
('19', '30', 'Resolved', NULL),
('29', '21', 'In Progress', '2024-06-09'),
('31', '21', 'Completed', '2024-08-04'),
('10', '39', 'Pending', '2024-09-01'),
('22', '2', 'Pending', '2024-02-21'),
('32', '39', 'Not Started', '2024-11-19'),
('12', '1', 'Open', '2024-09-01'),
('22', '22', 'Resolved', '2024-06-04'),
('2', '29', 'In Progress', '2024-02-07'),
('11', '2', 'Not Started', '2024-01-06'),
('20', '24', 'Open', '2024-10-03'),
('21', '4', 'Resolved', NULL),
('34', '24', 'Open', '2024-10-12'),
('13', '40', 'Resolved', '2024-06-10');

-- Issue Report Data
INSERT INTO issue_report
VALUES
('9', NULL, 'In Progress', 'Loss participant goal forward condition in. Receive individual during.'),
('26', '3', 'Completed', 'Help region road character performance. Bed candidate despite draw chair front still.'),
('16', NULL, 'Completed', 'Mission example news. Officer guess support hit. And place campaign as.'),
('1', '5', 'In Progress', 'Cover mind policy financial board people. Address talk later strong.'),
('36', '5', 'In Progress', 'Recognize board war be TV. Science player oil whom. Sort in should feeling thought.'),
('28', '3', 'Not Started', 'And huge total enjoy agree. Prove rich offer student evening rich cover.'),
('11', '1', 'Resolved', 'Until alone table whether. Wait imagine total collection charge source also hear.'),
('34', NULL, 'In Progress', 'Many outside hot language scene thousand. Listen campaign black.'),
('23', NULL, 'Completed', 'Happy us how. Full you economy generation care he moment. Once drop mouth would may little perform.'),
('27', NULL, 'Resolved', 'Listen they item former already sea seven staff. Lead head wind fine home.'),
('20', NULL, 'Resolved', 'Continue move nature story. Per right opportunity. Guess upon why minute.'),
('36', NULL, 'Open', 'Believe speak capital east. Job save nice too usually rise staff conference.'),
('6', NULL, 'Not Started', 'Up why authority concern century half or.'),
('17', '6', 'Resolved', 'Generation hold remember apply oil team suddenly.'),
('33', NULL, 'In Progress', 'End forget your when significant read present. History successful deep alone administration if.'),
('13', '1', 'Not Started', 'Few miss action.'),
('22', '7', 'Resolved', 'And discussion beat modern. Grow money throughout open product let mouth.'),
('6', '7', 'Open', 'Why education positive material event risk. Sit I fine three.'),
('16', NULL, 'Completed', 'Serve lay wife south reach property follow.'),
('27', NULL, 'Pending', 'Entire memory difficult leg instead read feel color. Summer lose save option.'),
('16', NULL, 'Open', 'Simple but season control end. Room interview every beat upon beat push.'),
('39', NULL, 'Resolved', 'Such edge pressure keep unit wind nearly mouth. Meet those either move gun present source.'),
('26', NULL, 'Pending', 'Huge job bit understand. Standard fish choose argue ever drive official. Always main space.'),
('27', '7', 'In Progress', 'Hand chance get.
Seem city should recent decision rather.'),
('22', NULL, 'Open', 'Assume show more popular. Ground bar though point.'),
('16', NULL, 'Pending', 'Business remember sign relationship local early. Drug action movement then.'),
('12', NULL, 'Resolved', 'During out minute. Apply whom support boy. And candidate oil value kid same whom.'),
('18', '5', 'Open', 'Fill parent political gun decade possible single wrong. Picture friend campaign management mother.'),
('39', NULL, 'Pending', 'Miss employee from explain. If table sound these.'),
('32', NULL, 'Pending', 'However view stuff say whole today. Student decide player standard change bad space.'),
('37', '1', 'Not Started', 'State particular bag crime watch. Plan film together commercial pass cultural.'),
('29', NULL, 'Completed', 'Toward economic sit impact. Explain material smile material.'),
('12', NULL, 'Not Started', 'Congress face national risk. Glass doctor read force red heavy.'),
('33', '3', 'Resolved', 'Skin sister would reduce theory. School full agency material dream contain issue statement.'),
('18', NULL, 'Open', 'Money brother fight difference. Good country imagine near.'),
('32', NULL, 'Not Started', 'Make boy short themselves yet. Chance design nothing nor.'),
('4', NULL, 'Completed', 'Effect body spend threat where challenge low suddenly.'),
('31', '8', 'In Progress', 'Professional argue college human. Industry begin girl husband top.'),
('24', NULL, 'Pending', 'Stand including sense cover agree. Former worry capital vote green.'),
('27', '7', 'Completed', 'Road them somebody wish. Stuff just chair cause pattern speech.');

-- Content Updates Data
INSERT INTO content_updates
VALUES
('27', '3', 'People feel suddenly environment then benefit source. Cold send gun both executive agent.'),
('39', '1', 'Question break a allow cup grow. While result future only. Make owner four official dark.'),
('21', '10', 'College race project other what time.'),
('14', '6', 'Decade be decision different protect girl. Right generation force class teach.'),
('11', '6', 'Treatment treatment really that. Nature he sort you example.'),
('19', '1', 'Wall rate network speak. Firm different area method.'),
('23', '2', 'Way writer simply exactly newspaper both ability. Model discover day.'),
('25', '8', 'Color wide low with paper happy. Attack cost floor all.'),
('11', '7', 'Language discussion issue small memory. Relationship act too admit school information.'),
('34', '8', 'Determine position unit and in office. Recognize marriage bed hit.'),
('34', '1', 'One front program usually federal physical draw. Down allow citizen charge share herself west.'),
('33', '5', 'Team commercial than realize concern senior. Benefit magazine democratic behind.'),
('11', '6', 'Together upon realize structure. Democratic management economy very memory.'),
('2', '7', 'Church single all miss care.'),
('35', '4', 'Western say per six forget once. Heart wear gas amount try.'),
('31', '8', 'Upon money manager himself the rest. Western too scientist treatment.'),
('19', '4', 'Discussion song may board. Talk onto environmental computer foot American finish.'),
('11', '3', 'Drug world school first protect foot first beat. Image land wide live toward trial.'),
('37', '3', 'Beautiful old study hair. Your baby speak. She increase line.'),
('17', '5', 'Agency fear month again service ago if.
Forget control very response white fund.'),
('12', '1', 'Message travel the marriage continue. Us so paper since risk scientist.'),
('26', '2', 'Seem sign both perform whatever. Pick southern usually wear.'),
('29', '3', 'True example far maybe. Picture loss send avoid.'),
('8', '6', 'Suddenly heavy image Democrat mouth community by.'),
('4', '4', 'Board rock ahead over human much guy. Air reach life thing show money.'),
('10', '10', 'Expect a environmental reach food think positive. Activity crime own trial note life research.'),
('1', '1', 'Court focus performance pick. Like news star blue radio area.'),
('26', '7', 'Similar base job stock.'),
('28', '6', 'Analysis form trip tax marriage drug. Trial century indeed prevent.'),
('15', '2', 'Partner by of serious accept police. Draw weight mission mission.'),
('36', '2', 'Whom show eat.'),
('27', '8', 'Actually mother reality everybody trip. Vote vote people type process. Each although pass however.'),
('12', '3', 'Artist ball class shake nothing. Power family condition.'),
('30', '7', 'Later mother vote put food war window. Course again together television.'),
('13', '6', 'East up thought four method my number light. Beautiful we student suffer actually unit.'),
('29', '4', 'Occur police type sport live officer century forward. Apply speak her claim at born.'),
('3', '9', 'Yet near behind the. Prevent human each throughout rather physical right card.'),
('29', '5', 'Stand add base quite. Open in treat production American well machine.'),
('1', '2', 'Remain federal student final improve. At partner than recent different but analysis.'),
('38', '8', 'Civil threat imagine will collection prepare loss everyone. Realize language able join prove.');

-- Session Data
INSERT INTO session
VALUES
('16', '22', 'Room carry teach member indicate course.', '2024-01-02', '02:41:00'),
('38', '13', 'Deep shoulder offer by official.', '2024-05-10', '02:48:00'),
('20', '25', 'Analysis big mouth nor spend one trial.', '2024-06-08', '03:39:00'),
('10', '3', 'Pm plant try really approach much majority send.', '2024-03-23', '02:50:00'),
('5', '23', 'Media material ten beyond author room.', '2024-09-13', '03:48:00'),
('26', '13', 'Democratic doctor budget his buy much.', '2024-07-17', '03:07:00'),
('31', '39', 'None production idea nature.', '2024-06-21', '03:59:00'),
('8', '27', 'Story recent purpose house.', '2024-02-12', '01:32:00'),
('39', '39', 'Style meet people production.', '2024-01-08', '00:01:00'),
('2', '26', 'Rather suffer program rise wind safe service.', '2024-02-07', '01:58:00'),
('27', '35', 'Watch example Mrs church real common remember.', '2024-11-19', '01:15:00'),
('9', '9', 'Mouth if old line. Life effect opportunity.', '2024-01-04', '02:10:00'),
('35', '1', 'Understand bag year foot.', '2024-09-17', '01:23:00'),
('27', '29', 'Method allow level else movement accept.', '2023-12-27', '02:44:00'),
('37', '7', 'Live view senior create adult lead hour open.', '2024-03-23', '03:36:00'),
('18', '36', 'Test series join.', '2024-02-14', '00:12:00'),
('5', '7', 'Debate stop affect attorney.', '2024-05-14', '02:37:00'),
('23', '35', 'Compare special beautiful wait institution.', '2024-01-27', '03:53:00'),
('1', '11', 'Huge former education lot night song provide.', '2024-09-27', '00:08:00'),
('2', '4', 'Speak while avoid song.', '2023-12-24', '02:12:00'),
('26', '6', 'Here while organization just else.', '2024-06-18', '01:58:00'),
('4', '28', 'With assume pull success catch table poor.', '2024-05-28', '00:27:00'),
('14', '39', 'Need recently cultural shake participant school.', '2024-09-25', '02:19:00'),
('13', '16', 'Week politics picture end wait thank thus.', '2024-06-09', '01:34:00'),
('32', '26', 'Product understand however keep media.', '2024-09-13', '03:22:00'),
('9', '34', 'Question senior Mr deep simply.', '2024-09-29', '01:22:00'),
('34', '26', 'Word notice standard return across.', '2024-03-18', '02:03:00'),
('8', '28', 'Laugh that once moment key really.', '2024-08-26', '00:59:00'),
('40', '28', 'Garden police down fast.', '2024-11-17', '03:54:00'),
('2', '24', 'Network southern place laugh.', '2024-08-31', '00:54:00'),
('17', '5', 'Paper soon foot million wait contain rich.', '2024-04-03', '01:14:00'),
('24', '35', 'Read reflect garden.', '2024-11-29', '03:07:00'),
('27', '16', 'Join current same carry people practice behind.', '2023-12-06', '03:19:00'),
('15', '13', 'Country spring build board drive.', '2024-10-06', '01:11:00'),
('6', '40', 'Right eat every local also how safe.', '2023-12-23', '02:15:00'),
('21', '40', 'Middle finally store service serious network.', '2024-09-03', '03:43:00'),
('18', '26', 'Space standard probably mouth organization.', '2024-01-30', '00:21:00'),
('23', '15', 'Management ball question government sing century.', '2024-11-24', '00:20:00'),
('14', '29', 'So city continue training.', '2024-02-23', '00:53:00'),
('23', '16', 'Miss meet reason realize third.', '2024-04-18', '01:42:00');

-- Feedback Data
INSERT INTO feedback
VALUES
('39', 'Should big such firm. Control book stop may arrive defense car physical.'),
('6', 'Stuff total deal its power. Police ball strategy finish. Serious through return message.'),
('13', 'Religious administration cell wife beyond. Situation since final commercial.'),
('11', 'Age few center analysis fact. Throw garden chance although section many.'),
('27', 'Could one plant inside chance door central. House song enter walk. Political draw white great.'),
('3', 'Also whatever long ever out behind improve. Various offer health may write within.'),
('15', 'Exist hard on receive. Fear out window light culture.'),
('10', 'Enter represent any me. Month suggest million whose after structure program.'),
('34', 'Feel set main nor beyond these. Strong site away common. Land worker old east safe.'),
('16', 'Account since these around evening I wife issue. Seven foot energy trade image.'),
('35', 'Foreign officer less require.'),
('17', 'That effect better travel well help policy. Through second TV or film civil Mrs.'),
('11', 'Project trouble fact tough job last goal.'),
('10', 'Former along mission. Want hear walk only message.'),
('27', 'Nothing soon day factor sport prove. Certain financial program state.'),
('34', 'Congress yourself full skin story. Modern drop small order spend.'),
('31', 'Keep these author remain management they. Certain someone lead under human run able.'),
('8', 'Future total argue miss. Wear civil bill operation crime indeed.'),
('35', 'None will behind east. Gas wide order safe. Kind number employee so maintain mention five.'),
('23', 'Everybody financial beautiful never tax. Trouble deal represent second.'),
('15', 'Born case within bar believe radio.'),
('3', 'Forget world way news sing feel. Conference beautiful court themselves control.'),
('1', 'Discussion though president hard. Bank suffer challenge community. Buy address role.'),
('7', 'Scene shoulder money watch performance. Total word old simply. Measure most close.'),
('19', 'Rock another pick figure home phone. Food character eight argue determine put than rate.'),
('13', 'Stand agreement oil long employee. Room that bar believe.'),
('10', 'Involve tend girl push professional wear network. Effort painting read identify for.'),
('9', 'Probably none offer. Join lead able occur bad design ground.'),
('19', 'Push but ability offer people where think ever. Tv compare provide most analysis.'),
('2', 'Evening religious budget oil professor decade budget.'),
('21', 'Form discussion marriage travel last center choose reveal.'),
('13', 'Detail indeed involve loss. If sit box work field.'),
('3', 'Building which identify society marriage computer quite.'),
('20', 'Without evidence usually she kind add impact. Candidate officer right front key the agent after.'),
('15', 'Out product vote professional sing research build. Fall news tonight would.'),
('36', 'Which peace weight less by several head. Throw sure fund language.'),
('15', 'International have tax company discover eight certain.'),
('20', 'Deal our smile author term environmental various back. Dream thousand draw pick people real.'),
('11', 'Week make group building alone spring happen them.'),
('21', 'Itself build between character message tax pass. Check by state.');

-- Scenario Practice Data
INSERT INTO scenario_practice
VALUES
('17', 'Must short different however hand.', 'Fluent'),
('3', 'From both finish. Again scientist eight should.', 'Advanced'),
('25', 'Pick capital industry travel not say.', 'Intermediate'),
('17', 'Increase now people.', 'Fluent'),
('22', 'Catch environmental future class important party.', 'Intermediate'),
('24', 'Action use also air modern act without home.', 'Fluent'),
('1', 'Or reality already seek couple choose room.', 'Advanced'),
('18', 'Stock miss lose phone.', 'Fluent'),
('36', 'Give put risk cell tree bill night.', 'Advanced'),
('31', 'Use authority writer activity some woman quite.', 'Intermediate'),
('10', 'Good quite student movie when rather.', 'Fluent'),
('13', 'Suffer newspaper outside protect.', 'Intermediate'),
('30', 'About human worry blood remember no send.', 'Beginner'),
('20', 'Action kid money without understand.', 'Intermediate'),
('4', 'If reality be old off day ahead.', 'Advanced'),
('12', 'Those consumer shake support about.', 'Intermediate'),
('36', 'Laugh anyone easy green could.', 'Intermediate'),
('8', 'Door child east official media market.', 'Beginner'),
('34', 'Night number poor sit born.', 'Advanced'),
('23', 'Position rather onto. Throw action cover.', 'Advanced'),
('31', 'Exist suggest peace according ground identify.', 'Intermediate'),
('19', 'Management full modern on music woman.', 'Fluent'),
('30', 'Them gas rich exactly would draw anything.', 'Fluent'),
('9', 'Little will season concern floor.', 'Advanced'),
('39', 'Father enter sometimes guess positive size.', 'Fluent'),
('14', 'Believe play summer letter hour new anything.', 'Intermediate'),
('7', 'Take make sing affect cost wonder evening moment.', 'Fluent'),
('3', 'Theory break use opportunity none.', 'Beginner'),
('26', 'Authority value federal address sing she ago.', 'Intermediate'),
('10', 'Road rise build order commercial beautiful.', 'Intermediate'),
('3', 'Skin type when nothing.', 'Beginner'),
('39', 'Begin each teacher address research mean light.', 'Intermediate'),
('39', 'House face effort understand hot all he continue.', 'Beginner'),
('37', 'Eat century second hour miss man summer but.', 'Beginner'),
('4', 'Room second put mother security call body toward.', 'Intermediate'),
('12', 'Important growth should end suffer we.', 'Beginner'),
('36', 'Program matter agent many religious teach.', 'Beginner'),
('8', 'Election mouth speech memory.', 'Fluent'),
('8', 'Be election stop baby baby.', 'Intermediate'),
('11', 'Fact provide industry theory.', 'Fluent');

-- Vocabulary Practice Data
INSERT INTO vocab_practice
VALUES
('25', 'Rest significant late report.', 'Fluent'),
('21', 'Instead board institution top owner.', 'Intermediate'),
('23', 'Heart hear sense top. We matter size spring.', 'Advanced'),
('35', 'Us house green really.', 'Fluent'),
('5', 'Mr pass such life.', 'Intermediate'),
('29', 'Position politics forget real election check.', 'Advanced'),
('8', 'Goal discover teach argue rate admit.', 'Intermediate'),
('25', 'Choice wear can study sign.', 'Fluent'),
('21', 'Future big become day.', 'Advanced'),
('31', 'Whether seek compare nation.', 'Advanced'),
('11', 'City lose contain hour with.', 'Advanced'),
('12', 'Despite anything itself court space artist.', 'Beginner'),
('32', 'Traditional team interesting across must peace.', 'Intermediate'),
('6', 'Least let agent simply difficult.', 'Fluent'),
('2', 'Beyond score move wrong part.', 'Beginner'),
('32', 'Election specific general however consider eye.', 'Fluent'),
('21', 'Check do specific story sometimes.', 'Fluent'),
('30', 'Once whole ask team.', 'Advanced'),
('36', 'Evening development return assume center.', 'Beginner'),
('12', 'Several foreign want box.', 'Fluent'),
('8', 'Candidate drop number drive wonder myself turn.', 'Fluent'),
('29', 'Outside type low cell town our teach.', 'Fluent'),
('10', 'Safe long contain Mrs wrong day upon operation.', 'Beginner'),
('35', 'Moment population because investment main.', 'Beginner'),
('26', 'Short real point school finally.', 'Advanced'),
('5', 'Modern image any save firm purpose voice.', 'Fluent'),
('14', 'Much assume movement wear while test power.', 'Intermediate'),
('37', 'Strategy allow rest what put mention.', 'Intermediate'),
('22', 'Claim despite affect.', 'Intermediate'),
('26', 'Month serve public admit.', 'Beginner'),
('18', 'Grow practice I every bag.', 'Advanced'),
('39', 'Lay report space two identify include research.', 'Advanced'),
('39', 'Human country factor during war.', 'Advanced'),
('1', 'Treatment popular stop.', 'Beginner'),
('3', 'Box give job station.', 'Intermediate'),
('25', 'Dinner allow similar air.', 'Fluent'),
('23', 'Far reveal thought American hard shoulder.', 'Intermediate'),
('25', 'Market affect ask country oil.', 'Intermediate'),
('13', 'Down by talk ask break.', 'Beginner'),
('11', 'Occur trial town involve.', 'Fluent');