INSERT INTO system_administrator VALUES
('john12@example.net', 'Lisa', 'Rocha', 'Content Manager'),
('galvancathy@example.net', 'Katherine', 'Proctor', 'Content Manager'),
('seth28@example.net', 'Nicholas', 'Harris', 'System Admin'),
('patricia64@example.org', 'Mark', 'Duke', 'Content Manager'),
('staceyfrazier@example.net', 'Natalie', 'Johnson', 'Support Specialist'),
('zevans@example.com', 'Allen', 'Wells', 'System Admin'),
('richardslaura@example.com', 'William', 'Larsen', 'System Admin'),
('cassie44@example.com', 'Jeffrey', 'Owens', 'Support Specialist'),
('krameramanda@example.com', 'Linda', 'Villegas', 'System Admin'),
('hmartinez@example.org', 'Margaret', 'Turner', 'System Admin');

-- Mentee Data
INSERT INTO mentee VALUES
('8', '8', 'Ralph', 'Ball', 'zmoss@example.com', 'Spanish', 'Beginner'),
('4', '1', 'Daniel', 'Johnson', 'lparker@example.com', 'French', 'Fluent'),
('4', '10', 'Jessica', 'Jenkins', 'mgreer@example.org', 'Japanese', 'Advanced'),
('6', '7', 'Robert', 'Porter', 'figueroadavid@example.net', 'Chinese', 'Fluent'),
('4', '6', 'Joseph', 'Castaneda', 'butlerjoshua@example.com', 'Japanese', 'Intermediate'),
('3', '1', 'Michael', 'Santiago', 'uwatkins@example.net', 'Spanish', 'Fluent'),
('1', '1', 'Sharon', 'Brown', 'keithjensen@example.com', 'Japanese', 'Intermediate'),
('2', '10', 'Brenda', 'Downs', 'cholmes@example.net', 'Japanese', 'Fluent'),
('7', '7', 'Dawn', 'Bowers', 'tjones@example.net', 'French', 'Intermediate'),
('6', '5', 'Crystal', 'Clark', 'ghobbs@example.org', 'Japanese', 'Fluent'),
('3', '9', 'Susan', 'Smith', 'robertyoung@example.net', 'Spanish', 'Beginner'),
('9', '2', 'Patricia', 'Haas', 'christopher15@example.net', 'French', 'Intermediate'),
('6', '3', 'Mark', 'Romero', 'kelleysarah@example.com', 'French', 'Advanced'),
('5', '9', 'Drew', 'Freeman', 'bcervantes@example.net', 'French', 'Advanced'),
('4', '3', 'Rebecca', 'George', 'jessicarichards@example.net', 'Spanish', 'Beginner'),
('6', '9', 'Sydney', 'Richards', 'james05@example.net', 'Japanese', 'Beginner'),
('1', '1', 'Lorraine', 'Terrell', 'kflynn@example.com', 'Japanese', 'Fluent'),
('2', '8', 'Chris', 'Mcmillan', 'phelpsthomas@example.com', 'Chinese', 'Beginner'),
('3', '4', 'Jessica', 'Chaney', 'jponce@example.net', 'Chinese', 'Advanced'),
('2', '6', 'Diane', 'Burgess', 'higginsseth@example.com', 'French', 'Beginner'),
('2', '5', 'Kim', 'Richards', 'berrykenneth@example.com', 'Japanese', 'Intermediate'),
('1', '1', 'David', 'Lane', 'josephchang@example.net', 'Japanese', 'Fluent'),
('2', '2', 'David', 'Norris', 'emily87@example.com', 'French', 'Intermediate'),
('10', '2', 'Susan', 'Ochoa', 'blake20@example.org', 'French', 'Beginner'),
('4', '10', 'Sean', 'Henderson', 'nrussell@example.net', 'French', 'Beginner'),
('3', '9', 'John', 'Barber', 'kathleen54@example.com', 'Spanish', 'Beginner'),
('4', '3', 'Eric', 'Hawkins', 'elizabeth49@example.com', 'Japanese', 'Fluent'),
('10', '3', 'Nicole', 'White', 'sierrawest@example.org', 'Chinese', 'Intermediate'),
('5', '1', 'Michael', 'Pugh', 'brewernichole@example.net', 'Spanish', 'Beginner'),
('10', '5', 'Emily', 'Scott', 'mariasullivan@example.org', 'Japanese', 'Beginner'),
('8', '2', 'Alicia', 'Conner', 'powellbrittany@example.net', 'French', 'Advanced'),
('3', '1', 'Vanessa', 'Tucker', 'patricktaylor@example.com', 'French', 'Beginner'),
('6', '8', 'Joshua', 'Miller', 'tammysimmons@example.net', 'Chinese', 'Fluent'),
('6', '6', 'Andrew', 'Shannon', 'fwatson@example.net', 'Spanish', 'Intermediate'),
('8', '5', 'Brian', 'Gardner', 'daniel44@example.net', 'Spanish', 'Beginner'),
('9', '7', 'Sarah', 'Kirby', 'emorris@example.com', 'Japanese', 'Fluent'),
('7', '2', 'Jason', 'Mann', 'morgancynthia@example.org', 'Japanese', 'Beginner'),
('6', '3', 'Mary', 'Gould', 'parksherry@example.net', 'Japanese', 'Intermediate'),
('7', '5', 'Caleb', 'Henderson', 'samuelcole@example.com', 'Chinese', 'Beginner'),
('5', '6', 'Caitlin', 'Matthews', 'everettlaura@example.org', 'Spanish', 'Beginner');

-- Mentor Data
INSERT INTO mentor VALUES
('2', '8', 'Richard', 'Hudson', 'kimberly75@example.net', 'French', 'Joelfurt, Timor-Leste', 'Advanced'),       
('1', '7', 'Kerry', 'Kennedy', 'ichen@example.net', 'Chinese', 'Hornebury, Bulgaria', 'Fluent'),
('2', '4', 'Tiffany', 'Johnson', 'jeremyhaynes@example.net', 'Japanese', 'East Kathryn, Mexico', 'Fluent'),     
('4', '10', 'Elizabeth', 'Jones', 'christine95@example.net', 'French', 'Johnstonbury, Malaysia', 'Advanced'),   
('3', '5', 'Charles', 'Miller', 'william29@example.org', 'Japanese', 'West Johnshire, Liberia', 'Advanced'),    
('8', '5', 'Joseph', 'Case', 'dcharles@example.net', 'Chinese', 'New John, Bolivia', 'Fluent'),
('6', '2', 'Mark', 'Sims', 'charles56@example.org', 'Japanese', 'Melissastad, Costa Rica', 'Fluent'),
('10', '4', 'Dominic', 'Terry', 'brandiosborne@example.com', 'Japanese', 'East Erinton, Chile', 'Advanced'),    
('3', '10', 'Diana', 'Powell', 'sanchezbryan@example.com', 'Japanese', 'Petersonmouth, United Kingdom', 'Fluent'),
('7', '6', 'Leslie', 'Hamilton', 'johnnygarza@example.net', 'French', 'Joshuamouth, Mozambique', 'Fluent'),     
('8', '6', 'Rachel', 'Mathis', 'ylin@example.org', 'French', 'Fletcherburgh, South Africa', 'Advanced'),        
('1', '5', 'Anna', 'Colon', 'john23@example.net', 'Chinese', 'North Jennifer, Reunion', 'Fluent'),
('3', '1', 'Jeffrey', 'Wells', 'melanie61@example.org', 'French', 'Williamberg, China', 'Advanced'),
('3', '2', 'Karen', 'Hess', 'juan02@example.org', 'Chinese', 'New Christopherborough, Libyan Arab Jamahiriya', 'Fluent'),
('1', '2', 'Amy', 'Harris', 'tiffanycastro@example.org', 'Chinese', 'New Joshua, Venezuela', 'Advanced'),       
('2', '7', 'Courtney', 'Mcdonald', 'brianshields@example.org', 'French', 'South Joyceburgh, Vanuatu', 'Fluent'),
('2', '7', 'Keith', 'Williams', 'joshua10@example.com', 'Japanese', 'Richardfort, Netherlands', 'Advanced'),    
('4', '10', 'Peter', 'Wagner', 'romerokyle@example.com', 'French', 'Kellyville, Venezuela', 'Advanced'),        
('3', '5', 'Crystal', 'Thompson', 'ybradley@example.net', 'Japanese', 'Patriciahaven, Bahamas', 'Advanced'),    
('9', '8', 'Tonya', 'Torres', 'joelstout@example.org', 'Japanese', 'East Melinda, Pakistan', 'Fluent'),
('5', '7', 'Sonya', 'Hill', 'mmartin@example.org', 'Spanish', 'South Jamie, Mayotte', 'Advanced'),
('4', '10', 'Keith', 'Cunningham', 'nbradley@example.net', 'Chinese', 'Terryville, Brazil', 'Fluent'),
('1', '10', 'Eric', 'Ashley', 'alexanderruth@example.org', 'Spanish', 'North Anthonyburgh, Israel', 'Advanced'),
('3', '8', 'Jessica', 'Russell', 'nguyenjeffrey@example.org', 'Chinese', 'Hendersonstad, Ireland', 'Fluent'),   
('7', '9', 'Doris', 'Morton', 'jamesrios@example.com', 'Chinese', 'Gilbertchester, Bahrain', 'Advanced'),       
('8', '9', 'Kelsey', 'Kennedy', 'jody44@example.com', 'Spanish', 'Juliaport, Belarus', 'Advanced'),
('3', '6', 'Denise', 'Reeves', 'carlosjordan@example.com', 'Japanese', 'Ramirezville, Libyan Arab Jamahiriya', 'Advanced'),
('10', '5', 'Brandon', 'Baker', 'robertcarter@example.net', 'French', 'Mollyborough, Samoa', 'Advanced'),       
('3', '4', 'Samantha', 'Davis', 'fferguson@example.org', 'French', 'New David, Czech Republic', 'Fluent'),      
('4', '2', 'Paula', 'Olsen', 'mrivera@example.com', 'Spanish', 'Daviesborough, Senegal', 'Advanced'),
('5', '7', 'Cory', 'Cole', 'millertracey@example.com', 'French', 'West Brandy, Netherlands Antilles', 'Fluent'),
('6', '8', 'Ian', 'Conner', 'mullenjustin@example.com', 'Spanish', 'South Heidi, Malaysia', 'Advanced'),        
('9', '4', 'Margaret', 'Esparza', 'awagner@example.com', 'Spanish', 'Port Darius, Cayman Islands', 'Fluent'),   
('1', '7', 'Rachael', 'Willis', 'skaufman@example.com', 'Japanese', 'New Joann, Seychelles', 'Advanced'),       
('3', '4', 'Jack', 'Jones', 'chris62@example.net', 'French', 'South Scott, Guam', 'Fluent'),
('10', '5', 'Nancy', 'Miller', 'hubertiffany@example.net', 'Spanish', 'South Samanthaville, Liechtenstein', 'Fluent'),
('3', '6', 'Carlos', 'Roth', 'anitamacias@example.com', 'French', 'Underwoodville, Puerto Rico', 'Fluent'),     
('9', '7', 'Rick', 'Robinson', 'ochen@example.net', 'Chinese', 'Port Mary, Bolivia', 'Advanced'),
('5', '9', 'Stacey', 'Huffman', 'arussell@example.net', 'Japanese', 'Gentryfort, Micronesia', 'Fluent'),        
('10', '5', 'Linda', 'Merritt', 'jeremyrodriguez@example.com', 'Spanish', 'Gonzalezhaven, Nigeria', 'Fluent');  

-- Learning Path Data
INSERT INTO learning_path VALUES
('31', '8', 'Module 2', 'Run pretty season because measure play focus.', 'Milestone 1, Milestone 2, Milestone 3', 'Pending'),
('2', '3', 'Module 5', 'Full never avoid central. Reveal as official my.', 'Milestone 1, Milestone 2, Milestone 3', 'Pending'),
('19', '8', 'Module 3', 'He despite look for case.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),      
('9', '8', 'Module 1', 'Detail house myself identify until his both.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('18', '10', 'Module 2', 'Thus issue several them current.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),  
('5', '1', 'Module 2', 'Strong thousand appear task culture old.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),
('17', '7', 'Module 5', 'Wall care method. Movement black vote mouth its.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),
('29', '3', 'Module 1', 'Add garden dinner season.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),   
('18', '4', 'Module 5', 'Your believe back.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('24', '2', 'Module 1', 'Civil eye direction network drug same.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('4', '9', 'Module 3', 'Never not a election person oil consider.', 'Milestone 1, Milestone 2, Milestone 3', 'Not Started'),
('24', '4', 'Module 3', 'Current as full next visit various.', 'Milestone 1, Milestone 2, Milestone 3', 'Pending'),
('20', '2', 'Module 3', 'Garden fast thank interview should.', 'Milestone 1, Milestone 2, Milestone 3', 'Pending'),
('29', '1', 'Module 5', 'Either expect democratic upon have.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),
('6', '5', 'Module 3', 'Wish west positive school hard want oil.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),
('10', '9', 'Module 5', 'Power grow area land recognize shake maybe.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('12', '4', 'Module 4', 'Color cold remain law everybody section.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),
('38', '5', 'Module 5', 'After upon number general.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),     
('33', '5', 'Module 3', 'Painting weight book high run.', 'Milestone 1, Milestone 2, Milestone 3', 'Pending'),  
('14', '1', 'Module 4', 'Plan them sometimes card before team.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),
('11', '10', 'Module 3', 'Sort soldier before security.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),     
('16', '10', 'Module 1', 'Same southern not produce upon perhaps.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('33', '3', 'Module 3', 'Begin thing owner. Similar thing develop laugh.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('39', '9', 'Module 2', 'Color fire population away research more.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('35', '1', 'Module 5', 'Early quality century safe anyone account.', 'Milestone 1, Milestone 2, Milestone 3', 'Pending'),
('8', '5', 'Module 2', 'Face agreement money court majority.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),
('15', '7', 'Module 5', 'Still relate technology friend son return.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('1', '1', 'Module 2', 'Fast eye life special control black.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),
('31', '8', 'Module 3', 'Special throughout design everyone where.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),
('12', '10', 'Module 3', 'Resource environmental let.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('17', '4', 'Module 3', 'Talk contain itself bed style minute.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),
('21', '10', 'Module 5', 'Military hear happen world effect.', 'Milestone 1, Milestone 2, Milestone 3', 'Completed'),
('15', '5', 'Module 1', 'Cold yeah guess security report national.', 'Milestone 1, Milestone 2, Milestone 3', 'Pending'),
('40', '4', 'Module 3', 'Very guy avoid may.', 'Milestone 1, Milestone 2, Milestone 3', 'Pending'),
('26', '1', 'Module 5', 'Size our air light.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),
('9', '7', 'Module 2', 'Skin skill perform act off ground.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),
('26', '2', 'Module 5', 'No too common add sea see will.', 'Milestone 1, Milestone 2, Milestone 3', 'In Progress'),
('7', '1', 'Module 1', 'Out address born interest enjoy police could.', 'Milestone 1, Milestone 2, Milestone 3', 'Open'),
('14', '6', 'Module 2', 'Design important study many.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved'),   
('15', '6', 'Module 1', 'Political final easy job popular finally work.', 'Milestone 1, Milestone 2, Milestone 3', 'Resolved');

-- Progress Data
INSERT INTO progress VALUES
('14', '17', 'Completed', '2024-11-01'),
('18', '10', 'In Progress', NULL),
('22', '10', 'Pending', '2024-03-19'),
('34', '7', 'Completed', '2024-11-05'),
('22', '39', 'In Progress', '2024-10-14'),
('4', '33', 'Pending', '2024-01-22'),
('14', '11', 'In Progress', '2024-02-24'),
('26', '40', 'Completed', NULL),
('20', '30', 'Not Started', '2024-06-02'),
('40', '19', 'Resolved', '2024-11-18'),
('15', '15', 'Open', NULL),
('17', '39', 'Completed', '2024-08-05'),
('34', '7', 'Completed', '2023-12-29'),
('2', '8', 'Completed', NULL),
('23', '26', 'Resolved', '2024-07-12'),
('30', '39', 'Open', NULL),
('24', '36', 'Completed', '2023-12-12'),
('36', '18', 'In Progress', '2024-02-09'),
('11', '39', 'Not Started', '2024-03-08'),
('19', '20', 'Completed', '2024-05-20'),
('37', '39', 'In Progress', '2024-06-29'),
('3', '1', 'Resolved', NULL),
('1', '20', 'Resolved', NULL),
('17', '21', 'Pending', NULL),
('15', '37', 'Resolved', '2024-12-04'),
('25', '22', 'Not Started', '2024-06-26'),
('6', '7', 'Resolved', '2023-12-08'),
('20', '30', 'Pending', NULL),
('15', '23', 'Not Started', NULL),
('33', '40', 'In Progress', '2024-10-04'),
('33', '32', 'Resolved', NULL),
('29', '20', 'Completed', '2024-05-12'),
('7', '26', 'Resolved', NULL),
('35', '10', 'Open', '2024-04-29'),
('8', '21', 'In Progress', NULL),
('12', '4', 'Open', '2024-04-15'),
('35', '5', 'Open', '2024-06-05'),
('28', '39', 'Not Started', NULL),
('40', '11', 'Not Started', '2024-01-24'),
('10', '26', 'Completed', '2023-12-10');

-- Issue Report Data
INSERT INTO issue_report VALUES
('24', '5', 'Open', 'Morning top process very point very. North free trial lose partner also group.'),
('15', NULL, 'Not Started', 'Without adult drug hope claim. Which factor government record site section third.'),
('40', '7', 'Pending', 'Chair or parent act. Land discussion maybe approach claim big. Protect seven step way.'),
('11', NULL, 'In Progress', 'World edge long like example all product. Quality point quickly likely. Such draw seven alone.'),
('34', NULL, 'In Progress', 'Say leg throw three seven for. Range pretty government effort.'),
('40', NULL, 'Resolved', 'Boy white contain form. Cause state oil beat thus.'),
('17', '10', 'Not Started', 'Available analysis then event. Student any cup case foot article.'),
('38', '6', 'In Progress', 'Voice peace maybe strategy southern capital. Consumer star most key sense boy.'),   
('28', '1', 'Completed', 'Across expert high carry however person.'),
('21', '7', 'Open', 'Particular president property the measure trade to. Company bar sort usually.'),
('5', '1', 'Resolved', 'Wall sense say after. Seek baby model police major first sign. Paper cover future compare.'),
('11', '2', 'Completed', 'Cause stand agree student run make. Top truth book draw billion.'),
('27', '6', 'Resolved', 'Member necessary high material administration. Body theory can they structure very.'), 
('9', '2', 'Not Started', 'Race staff five though. Score authority her wrong. Song compare talk.'),
('30', NULL, 'Open', 'Beautiful several increase garden free. There group bit new student almost.'),
('31', NULL, 'Not Started', 'Letter chair if under. Into rich important trip.'),
('2', '1', 'Pending', 'Of peace hear. Will partner like baby. Body operation room daughter mention work must.'),
('29', NULL, 'Resolved', 'Prevent sign short follow shoulder health. Free various about.'),
('26', '3', 'Pending', 'Tax so forward pressure four. Try court until else teach movie any show.'),
('26', NULL, 'Not Started', 'Analysis claim second. Morning firm much action two civil.'),
('37', NULL, 'Resolved', 'See figure second. Generation eye build like arm.'),
('1', NULL, 'Completed', 'Song guy it deal join. Movement rate kind sure choice drop.'),
('11', NULL, 'Resolved', 'Firm take actually property movement. Her store when. Black control realize test necessary.'),
('18', '4', 'Resolved', 'Really business together likely. Opportunity after blue. Specific population sign morning this.'),
('39', '8', 'Completed', 'Eat drop home people likely interest care in. And walk group include seat protect can.'),
('4', NULL, 'Not Started', 'Itself significant inside field bank force arrive. Recognize kid interest take could cause.'),
('21', NULL, 'In Progress', 'Car kitchen discussion car. The teach son suggest wait marriage.'),
('19', NULL, 'Open', 'Religious improve when garden choose focus I on. Mother others its lead agent our.'),     
('6', '6', 'Completed', 'Thank baby order heavy group likely within. Choice try event push scene daughter.'),   
('21', '10', 'Pending', 'Bag large a. Produce term seek tend. Window yourself resource.'),
('33', '1', 'Not Started', 'Seven purpose talk control cause likely. Enough clearly friend nearly writer program again.'),
('29', NULL, 'Resolved', 'Less job because call. Happen public ok memory industry.'),
('18', '1', 'In Progress', 'However doctor about summer soon bring. Mind option board sort which with order claim.'),
('33', '4', 'Pending', 'Idea police catch. Kind issue majority newspaper condition all design.'),
('7', NULL, 'Completed', 'Yet natural notice guy. Worker structure program attention reflect.
Both chance white energy away.'),
('38', '9', 'Open', 'Population yard design letter. Suggest discussion red receive eat people southern nation.'),
('18', NULL, 'Completed', 'Popular end poor site goal risk apply. Base help throw understand. Pass show there.'),
('9', NULL, 'Open', 'Kitchen moment message statement. Clearly large cold growth floor important.'),
('38', '1', 'Pending', 'Physical picture industry case.'),
('7', NULL, 'In Progress', 'Expect member have action chair nice tax. Positive pay majority American himself play.');

-- Content Updates Data
INSERT INTO content_updates VALUES
('22', '1', 'Large billion entire far. Much threat number offer defense major.'),
('30', '2', 'Day require machine table. Beyond term public identify dream might.'),
('12', '7', 'Subject item material. Very skin home of sometimes. None agent turn case really which end.'),      
('29', '4', 'Test you series its size. Reach since involve make state itself Democrat especially.'),
('14', '4', 'Present glass skin song thought recent resource tax.'),
('35', '5', 'Church care catch city guy large few. Will officer of suffer industry blue front.'),
('22', '1', 'Admit sister teach entire economic relate cut. Magazine radio few matter product.'),
('19', '4', 'Decide far glass ability. Poor develop vote figure do not. Shoulder gas girl at.'),
('24', '2', 'Ask anything TV result must. Road three environment real for campaign boy.'),
('23', '8', 'Quality pattern crime hear white. Difference hard full sell save represent than. Pull run detail.'),
('2', '4', 'Action strong author moment. Short role international hair trial grow continue.'),
('24', '1', 'Could paper weight ball rather anyone. Tree arrive somebody suffer college.'),
('4', '5', 'Law standard board. Relationship arm money suddenly kid food.'),
('34', '9', 'Management store foot wear. Somebody true pass then.'),
('14', '3', 'Nation determine available anyone worry international international. And guy meet property.'),     
('29', '9', 'End safe issue score see sit year need. Over degree entire job pay stop book number.'),
('12', '10', 'Step TV leader development test role thousand resource. Ok beautiful when question.'),
('21', '1', 'He lay effort receive. Receive research front catch so hundred. Else election imagine.'),
('11', '8', 'Newspaper key store prevent control some all.'),
('8', '4', 'Fish course degree cut difficult common decide establish. Put past check news develop both budget.'),
('35', '3', 'Mean gun cost may size. Painting off serious.'),
('35', '6', 'Really under truth traditional have.'),
('8', '9', 'Live the nice difference by. There meeting effort choice.'),
('38', '2', 'History even specific event. Become high reflect lot step serve site gas.'),
('15', '5', 'Quite drug cultural keep us laugh find include. Picture when Congress financial same kid.'),       
('24', '1', 'Reflect add follow media get wonder finally. Let stop good increase hot. Begin visit certain stock.'),
('11', '1', 'Force believe pretty over. Will box become government could.'),
('9', '7', 'Tonight news turn. Billion environment billion number order final go.'),
('23', '5', 'These talk town meet. Car keep after just. Term enjoy treat respond.'),
('39', '8', 'Bring game they next exactly watch various. Public down upon low service nature main city.'),      
('10', '6', 'Traditional TV eat. Current pattern data prepare event.'),
('40', '2', 'Raise outside board per key air experience commercial. Discuss then long maintain as.'),
('38', '4', 'Media blue detail decide receive. New its soon past. Run author million point poor price her.'),   
('30', '10', 'Mention wife major reality. Large seek far moment need floor agree.'),
('13', '10', 'Though past board consider indicate single. Offer attention by sell science generation door.'),   
('33', '2', 'Cut exactly industry rise you. Manage camera light ground argue thing very. Some can able.'),      
('25', '9', 'Treatment kitchen our sometimes issue later mother despite. Meeting position almost above.'),      
('36', '3', 'Shake determine glass score stay argue. One pass avoid deep bill. Material allow continue.'),      
('25', '10', 'Record able couple whole child lay catch. Hope between situation bar full method those reach.'),  
('13', '7', 'Central face despite everyone product entire receive. Vote as everything war city consumer dinner.');

-- Session Data
INSERT INTO session VALUES
('4', '34', 'Animal buy minute deep sense this.', '2023-12-06', '03:24:00'),
('10', '29', 'Project member big catch.', '2024-01-01', '00:59:00'),
('11', '34', 'Social interview beautiful alone.', '2024-01-06', '02:31:00'),
('13', '35', 'Short structure either health.', '2024-04-06', '00:00:00'),
('27', '22', 'Inside cut information whom quickly hot.', '2024-02-10', '01:46:00'),
('23', '8', 'Dark until almost southern very.', '2024-10-31', '01:25:00'),
('12', '34', 'These defense late line benefit single message.', '2024-08-20', '03:24:00'),
('26', '32', 'Almost investment teach few several democratic.', '2024-11-26', '00:05:00'),
('4', '2', 'Kind foot center view blood song.', '2024-07-01', '01:26:00'),
('34', '2', 'Shoulder pressure marriage long.', '2024-06-19', '01:17:00'),
('35', '5', 'Question mean reality hour. Woman senior grow.', '2024-02-21', '03:42:00'),
('19', '21', 'Call story single according can.', '2024-04-25', '00:13:00'),
('38', '22', 'Baby her court sport type vote.', '2024-10-28', '03:14:00'),
('19', '37', 'Not early similar body enough skin to.', '2024-10-04', '02:43:00'),
('8', '39', 'Back color parent reality power why.', '2024-03-07', '02:26:00'),
('10', '33', 'Congress should over as time.', '2024-01-20', '03:01:00'),
('37', '19', 'Successful paper laugh well.', '2024-05-19', '01:59:00'),
('10', '27', 'Support bag direction when program again.', '2024-02-27', '02:41:00'),
('3', '38', 'Condition blood forget relationship machine.', '2024-10-06', '02:07:00'),
('23', '2', 'Theory so right television tough avoid represent.', '2024-06-09', '01:01:00'),
('16', '2', 'Democratic bag language thought.', '2024-03-16', '00:19:00'),
('18', '19', 'Serve behavior large agent.', '2024-11-15', '02:13:00'),
('4', '39', 'Culture agency detail institution up even vote.', '2024-01-25', '01:24:00'),
('23', '11', 'Family amount office.', '2024-03-13', '02:08:00'),
('30', '40', 'Across suggest indeed safe.', '2024-03-28', '01:40:00'),
('5', '6', 'Goal around five better organization part do.', '2024-11-01', '00:13:00'),
('4', '40', 'Camera expect audience protect among.', '2024-11-28', '02:16:00'),
('2', '4', 'Left rule authority mind.', '2024-04-18', '01:20:00'),
('24', '16', 'Contain particular develop there dark fight.', '2023-12-30', '00:52:00'),
('31', '24', 'Suffer road American want.', '2024-09-10', '01:30:00'),
('19', '20', 'Continue his admit receive ten those.', '2024-11-08', '03:00:00'),
('18', '32', 'Arrive officer discover option.', '2023-12-05', '01:28:00'),
('21', '11', 'They tree clearly five.', '2023-12-30', '01:28:00'),
('33', '17', 'Success blood effort benefit.', '2024-09-13', '03:07:00'),
('33', '15', 'Energy action fact stage run small myself.', '2024-03-19', '03:42:00'),
('21', '10', 'Plan down week break close through.', '2024-04-03', '02:58:00'),
('20', '21', 'Art available change force training.', '2024-02-12', '00:37:00'),
('26', '4', 'Face senior analysis option.', '2024-09-10', '03:58:00'),
('14', '38', 'Unit mean dog time rock name usually.', '2024-11-15', '03:53:00'),
('29', '19', 'Agent partner sport laugh source away.', '2024-08-14', '00:50:00');

-- Feedback Data
INSERT INTO feedback VALUES
('36', 'Likely others Republican answer run. Home detail medical his story notice seem other.'),
('19', 'Share improve change. Whole by south focus certainly.'),
('34', 'Actually bar behind model day.'),
('16', 'Son decade movie thing quality yard prevent speak. Own across modern. Eat before song.'),
('2', 'Vote next lay. Build its soldier off. Although his five perform.'),
('27', 'Stock market discover investment performance to near. Event part memory anything seem population.'),    
('30', 'Tree stay group free. Lot city middle over.'),
('17', 'Term receive include spend huge very these. Daughter others agency.'),
('31', 'Away because director Congress enough research. Be do bar will.'),
('14', 'Us after seem you type activity water.'),
('14', 'Unit above decide adult. Floor available card maintain early. Two east kind firm.'),
('5', 'Police class more business take inside friend. Upon her certainly story.'),
('7', 'Alone include threat safe feel try during. Five mouth than southern.'),
('2', 'Although since consider concern significant often every. Listen vote data according friend evening.'),   
('18', 'Federal mission federal expert. Maintain set recently side positive seven.'),
('25', 'Cause finally particular almost unit turn. Occur me maintain room continue.'),
('29', 'Near gun issue you glass. Think east follow hair issue reality top.'),
('34', 'Difference though site talk cultural no hit. Decide to commercial alone.'),
('32', 'Full church gun training.
Raise attorney drug month. City seek learn suggest.'),
('32', 'Field sort either sign real citizen. Lose account two test. Exactly a high music buy under.'),
('23', 'Answer large different. Girl perhaps your case. Age less hard we father whose along.'),
('12', 'Project total scientist look. Station federal center should. Friend offer attention season.'),
('40', 'Wonder heart agreement free close.'),
('17', 'Our bit state guy early increase each how. Ahead recognize fast main a involve against.'),
('14', 'Remain population road one hour. Item debate from worker grow.'),
('5', 'Result reason crime far black.'),
('16', 'Teach at try brother early beautiful hotel party. Letter mind seem party hot.'),
('16', 'Country later southern song.'),
('6', 'Collection black force tell. Cold skill use daughter note.'),
('34', 'Go evidence little that evidence senior along. Boy TV ability. High present property.'),
('19', 'Station instead shake father she later answer. Whole born wear argue.'),
('27', 'While car tree describe. Ok right player star any reveal child.'),
('27', 'Manager once quite. Issue usually sell box million read. Condition once beat machine follow.'),
('10', 'Long notice only energy save somebody. Single test live sure floor still film. Stand mouth mission.'),  
('33', 'Administration article than likely charge.
Worker can unit sell. Serve school above everyone.'),
('23', 'Crime recognize science station begin people wife.'),
('29', 'Trouble maybe child speech front cold lay. Join design protect speak.'),
('15', 'Tv drive usually here peace fire. Administration under sometimes just moment want image.'),
('19', 'Reality very among between successful election. Expect I third name quite analysis.'),
('37', 'Major actually last race campaign. Reveal key visit five.');

-- Scenario Practice Data
INSERT INTO scenario_practice VALUES
('22', 'With certainly from garden.', 'Beginner'),
('4', 'Space morning ten treat quite.', 'Advanced'),
('1', 'Sure floor friend sell administration.', 'Fluent'),
('16', 'I response artist. Poor off loss.', 'Fluent'),
('32', 'Land off rate model finish.', 'Fluent'),
('39', 'These community bank.', 'Advanced'),
('28', 'Door own term kitchen though ago mention lead.', 'Fluent'),
('36', 'Voice boy song collection four.', 'Fluent'),
('5', 'Attention toward air executive various.', 'Fluent'),
('5', 'Way event visit. Color be guess.', 'Fluent'),
('20', 'Oil while feel outside partner approach.', 'Intermediate'),
('28', 'Present fear right account quality report.', 'Advanced'),
('25', 'Stop interest focus else head truth.', 'Advanced'),
('16', 'At single drug organization.', 'Advanced'),
('20', 'Administration argue subject later here modern.', 'Beginner'),
('16', 'Card more force attorney drive improve issue.', 'Intermediate'),
('34', 'Term to area account into house possible.', 'Beginner'),
('20', 'Or kitchen scientist man what.', 'Advanced'),
('23', 'Son first market score store.', 'Advanced'),
('20', 'Finish put fast activity perhaps both believe.', 'Fluent'),
('30', 'Go west day speech but.', 'Fluent'),
('13', 'View then blue fill bit best.', 'Intermediate'),
('40', 'Lay use picture that. Than know those truth.', 'Advanced'),
('12', 'Drug social show table oil gun party.', 'Advanced'),
('3', 'Court success campaign strategy power.', 'Advanced'),
('20', 'During town stop strategy though.', 'Intermediate'),
('29', 'Rather win draw.', 'Beginner'),
('35', 'Citizen true apply tough.', 'Intermediate'),
('10', 'Including military scene read international.', 'Fluent'),
('4', 'Particular ready cultural that seek.', 'Beginner'),
('24', 'Read class treatment race. Much Mrs manage year.', 'Beginner'),
('25', 'Yet race police along wide son.', 'Beginner'),
('22', 'Page stock fact task note you.', 'Beginner'),
('39', 'There rock smile see begin soon choose.', 'Beginner'),
('6', 'Large compare entire voice continue.', 'Fluent'),
('6', 'My pull market forget last.', 'Intermediate'),
('26', 'Write wear picture food not analysis.', 'Fluent'),
('36', 'Fall five yet fall.', 'Fluent'),
('14', 'Main here gun same.', 'Intermediate'),
('19', 'Into vote final.', 'Beginner');

-- Vocabulary Practice Data
INSERT INTO vocab_practice VALUES
('12', 'Reflect raise provide push new they seven.', 'Fluent'),
('15', 'Girl young writer court view generation.', 'Advanced'),
('33', 'Garden she natural successful top prove why wait.', 'Fluent'),
('26', 'After factor itself finish.', 'Advanced'),
('30', 'Responsibility well reason.', 'Fluent'),
('39', 'Through sense executive compare.', 'Beginner'),
('13', 'Type beautiful meet she lot picture.', 'Beginner'),
('24', 'Seat teacher example. Difficult use job product.', 'Advanced'),
('11', 'Agent song still forward character century yard.', 'Intermediate'),
('5', 'Economic bad them property.', 'Fluent'),
('38', 'Read huge consider family face.', 'Intermediate'),
('16', 'Education three since last green play break.', 'Fluent'),
('39', 'Energy rule win truth tend.', 'Intermediate'),
('5', 'Order financial per section if thank start.', 'Intermediate'),
('2', 'Less rich newspaper number.', 'Advanced'),
('23', 'Discover too else we election.', 'Fluent'),
('22', 'This without call.', 'Advanced'),
('21', 'Million by cover low effort class like.', 'Intermediate'),
('19', 'Material herself reason about practice edge.', 'Beginner'),
('17', 'Debate among throw seem.', 'Advanced'),
('9', 'Expert moment have even director might capital.', 'Beginner'),
('30', 'Daughter they black cover hot speech.', 'Fluent'),
('3', 'Mention appear grow notice per myself.', 'Intermediate'),
('1', 'Why crime charge outside whose term.', 'Intermediate'),
('5', 'Process yes accept eight.', 'Fluent'),
('17', 'Point condition once great.', 'Beginner'),
('3', 'Save staff set write.', 'Advanced'),
('8', 'Physical writer base forward here.', 'Fluent'),
('35', 'Score visit few half have.', 'Advanced'),
('40', 'Meet space control five.', 'Advanced'),
('5', 'Admit grow as then increase hot.', 'Advanced'),
('32', 'Society baby beautiful player talk up.', 'Intermediate'),
('8', 'Common view account picture.', 'Intermediate'),
('25', 'Meeting from process special economy.', 'Advanced'),
('20', 'Research according sit with.', 'Fluent'),
('5', 'Guess business mission community whose day chair.', 'Intermediate'),
('7', 'Officer off where decide reach.', 'Advanced'),
('14', 'Show attention painting human.', 'Beginner'),
('4', 'Room outside difficult executive.', 'Beginner'),
('20', 'Much change wind yet hope medical.', 'Beginner');